import { ICategory } from '@/interfaces/category.interface'

export const categoriesData: ICategory[] = [
	{
		title: 'Допомога',
		img: 'category/help.png',
		color: '#f2f3f5',
		link: '/help',
		subcategories: [
			{
				title: 'Потрібна допомога',
				link: '/need-help',
				subcategories: [
					{
						title: 'Ліки та Гігієнічні засоби',
					},
					{
						title: 'Житло',
					},
					{
						title: 'Транспорт',
					},
					{
						title: 'Для дітей',
					},
					{
						title: 'Одяг та взуття',
					},
					{
						title: 'Для тварин',
					},
					{
						title: 'Медична допомога',
					},
					{
						title: 'Їжа / Продукти',
					},
					{
						title: 'Інше',
					},
				],
			},
			{
				title: 'Пропоную допомогу',
				link: 'offer-help',
				subcategories: [
					{
						title: 'Ліки та Гігієнічні засоби',
					},
					{
						title: 'Житло',
					},
					{
						title: 'Транспорт',
					},
					{
						title: 'Для дітей',
					},
					{
						title: 'Одяг та взуття',
					},
					{
						title: 'Для тварин',
					},
					{
						title: 'Медична допомога',
					},
					{
						title: 'Їжа / Продукти',
					},
					{
						title: 'Інше',
					},
				],
			},
		],
	},
	{
		title: 'Дитячий світ',
		img: 'category/children.png',
		color: '#3a77ff',
		link: '/children_world',
		subcategories: [
			{
				title: 'Дитячі коляски',
				link: '/strollers',
			},
			{
				title: 'Дитячі меблі',
				link: '/furniture',
			},
			{
				title: 'Інші дитячі товари',
				link: '/other',
			},
			{
				title: 'Дитячі автокрісла',
				link: '/car-seats',
			},
			{
				title: 'Дитячий одяг',
				link: '/clothing',
				subcategories: [
					{
						title: 'Одяг для хлопчиків',
					},
					{
						title: 'Одяг для дівчаток',
					},
					{
						title: 'Одяг для новонароджених',
					},
				],
			},
			{
				title: 'Дитяче взуття',
				link: '/shoes',
			},
			{
				title: 'Іграшки',
				link: '/toys',
				subcategories: [
					{
						title: 'Конструктори',
					},
					{
						title: 'Ляльки та пупси',
					},
					{
						title: 'Аксесуари для ляльок та пупсів',
					},
					{
						title: 'Розвиваючі іграшки',
						subcategories: [
							{
								title: 'Мозаїки',
							},
							{
								title: 'Іграшки сортери',
							},
							{
								title: 'Інтерактивні іграшки',
							},
							{
								title: 'Бізіборди та куби',
							},
							{
								title: 'Ігрові центри',
							},
							{
								title: 'Дзиги',
							},
							{
								title: 'Іграшки неваляшки',
							},
							{
								title: 'Іграшки каталки',
							},
							{
								title: 'Музичні інструменти',
							},
							{
								title: 'Розвиваючі килимки',
							},
							{
								title: 'Інші розвиваючі ігри',
							},
						],
					},
					{
						title: "М'які іграшки",
						subcategories: [
							{
								title: "М'які тварини",
							},
							{
								title: 'Іграшки-подушки',
							},
							{
								title: "Інші м'які іграшки",
							},
						],
					},
					{
						title: 'Настільні ігри та пазли',
						subcategories: [
							{
								title: 'Пазли',
							},
							{
								title: '3D-пазли',
							},
							{
								title: 'Дитячі головоломки',
							},
							{
								title: 'Дитячі настільні ігри',
							},
							{
								title: 'Інші настільні ігри',
							},
						],
					},
					{
						title: 'Брязкальця та підвіски',
					},
					{
						title: 'Іграшки для купання',
					},
					{
						title: 'Іграшкова зброя',
						subcategories: [
							{
								title: 'Пістолети',
							},
							{
								title: 'Автомати',
							},
							{
								title: 'Бластери',
							},
							{
								title: 'Мечі та щити',
							},
							{
								title: 'Луки та арбалети',
							},
							{
								title: 'Водяна зброя',
							},
							{
								title: 'Інша іграшкова зброя',
							},
						],
					},
					{
						title: 'Ігрові фігурки',
						subcategories: [
							{
								title: 'Фігурки персонажів',
							},
							{
								title: 'Фігурки тварин',
							},
							{
								title: 'Інші фігурки',
							},
						],
					},
					{
						title: 'Іграшковий транспорт',
						subcategories: [
							{
								title: 'Залізниці та потяги',
							},
							{
								title: 'Машинки',
							},
							{
								title: 'Мотоцикли',
							},
							{
								title: 'Танки',
							},
							{
								title: 'Гелікоптери',
							},
							{
								title: 'Трактори',
							},
							{
								title: 'Літаки',
							},
							{
								title: 'Інший іграшковий транспорт',
							},
						],
					},
					{
						title: 'Набори для творчості',
					},
					{
						title: 'Ігрові набори',
						subcategories: [
							{
								title: 'Косметика для дівчаток',
							},
							{
								title: 'Набори професій',
							},
							{
								title: 'Дитячі кухні',
							},
							{
								title: 'Інші ігрові набори',
							},
						],
					},
					{
						title: 'Іграшки для пісочниці',
					},
					{
						title: "Дитячі м'ячі",
					},
					{
						title: 'Дитячі маски',
					},
					{
						title: 'Інші іграшки для дітей',
					},
				],
			},
			{
				title: 'Годування',
				link: '/feeding',
			},
			{
				title: 'Товари для школярів',
				link: '/school-supplies',
			},
			{
				title: 'Дитячий транспорт',
				link: '/transport',
			},
		],
	},
	{
		title: 'Нерухомість',
		img: 'category/real-estate.png',
		color: '#23e5db',
		link: '/real-estate',
		subcategories: [
			{
				title: 'Подобова оренда житла',
				link: '/daily',
				subcategories: [
					{
						title: 'Будинки подобово, погодинно',
					},
					{
						title: 'Квартири подобово, погодинно',
					},
					{
						title: 'Кімнати подобово, погодинно',
					},
					{
						title: 'Готелі, бази відпочинку',
					},
					{
						title: 'Хостели, койко-місця',
					},
					{
						title: 'Пропозиції Туроператорів',
					},
				],
			},
			{
				title: 'Будинки',
				link: '/houses',
				subcategories: [
					{
						title: 'Продаж будинків',
					},
					{
						title: 'Довгострокова оренда будинків',
					},
				],
			},
			{
				title: 'Нерухомість за кордоном',
				link: '/abroad',
			},
			{
				title: 'Земля',
				link: '/land',
				subcategories: [
					{
						title: 'Оренда землі',
					},
					{
						title: 'Продаж землі',
					},
				],
			},
			{
				title: 'Комерційна нерухомість',
				link: '/commercial',
				subcategories: [
					{
						title: 'Продаж комерційної нерухомості',
					},
					{
						title: 'Оренда комерційної нерухомості',
					},
					{
						title: 'Коворкінги',
					},
				],
			},
			{
				title: 'Гаражі, парковки',
				link: '/garages',
				subcategories: [
					{
						title: 'Оренда гаражів, парковок',
					},
					{
						title: 'Продаж гаражів, парковок',
					},
				],
			},
			{
				title: 'Кімнати',
				link: '/rooms',
				subcategories: [
					{
						title: 'Продаж кімнат',
					},
					{
						title: 'Довгострокова оренда кімнат',
					},
				],
			},
			{
				title: 'Квартири',
				link: '/apartments',
				subcategories: [
					{
						title: 'Продаж квартир',
					},
					{
						title: 'Довгострокова оренда квартир',
					},
				],
			},
		],
	},
	{
		title: 'Авто',
		img: 'category/auto.png',
		color: '#ff5636',
		link: '/transport',
		subcategories: [
			{
				title: 'Легкові автомобілі',
				link: '/cars',
				subcategories: [
					{ title: 'Acura' },
					{ title: 'Alfa Romeo' },
					{ title: 'Aston Martin' },
					{ title: 'Audi' },
					{ title: 'Bentley' },
					{ title: 'BMW' },
					{ title: 'BMW-Alpina' },
					{ title: 'Brilliance' },
					{ title: 'Buick' },
					{ title: 'BYD' },
					{ title: 'Cadillac' },
					{ title: 'Chana' },
					{ title: 'Chery' },
					{ title: 'Chevrolet' },
					{ title: 'Chrysler' },
					{ title: 'Citroen' },
					{ title: 'Dacia' },
					{ title: 'Dadi' },
					{ title: 'Daewoo' },
					{ title: 'Daihatsu' },
					{ title: 'Dodge' },
					{ title: 'FAW' },
					{ title: 'Ferrari' },
					{ title: 'Fiat' },
					{ title: 'Ford' },
					{ title: 'Geely' },
					{ title: 'GMC' },
					{ title: 'Great Wall' },
					{ title: 'Groz' },
					{ title: 'Honda' },
					{ title: 'Hummer' },
					{ title: 'Hyundai' },
					{ title: 'Infiniti' },
					{ title: 'Isuzu' },
					{ title: 'Iveco' },
					{ title: 'JAC' },
					{ title: 'Jaguar' },
					{ title: 'Jeep' },
					{ title: 'Kia' },
					{ title: 'Lamborghini' },
					{ title: 'Lancia' },
					{ title: 'Land Rover' },
					{ title: 'Lexus' },
					{ title: 'Lifan' },
					{ title: 'Lincoln' },
					{ title: 'Lotus' },
					{ title: 'Maserati' },
					{ title: 'Maybach' },
					{ title: 'Mazda' },
					{ title: 'McLaren' },
					{ title: 'Mercedes-Benz' },
					{ title: 'Mercury' },
					{ title: 'MG' },
					{ title: 'MINI' },
					{ title: 'Mitsubishi' },
					{ title: 'Nissan' },
					{ title: 'Oldsmobile' },
					{ title: 'Opel' },
					{ title: 'Peugeot' },
					{ title: 'Pontiac' },
					{ title: 'Porsche' },
					{ title: 'Proton' },
					{ title: 'Ram' },
					{ title: 'Ravon' },
					{ title: 'Renault' },
					{ title: 'Rolls-Royce' },
					{ title: 'Roewe' },
					{ title: 'Rover' },
					{ title: 'Saab' },
					{ title: 'Samand' },
					{ title: 'Samsung' },
					{ title: 'Seat' },
					{ title: 'Shelby' },
					{ title: 'Skoda' },
					{ title: 'Smart' },
					{ title: 'SsangYong' },
					{ title: 'Subaru' },
					{ title: 'Suzuki' },
					{ title: 'TATA' },
					{ title: 'Tesla' },
					{ title: 'Toyota' },
					{ title: 'Volkswagen' },
					{ title: 'Volvo' },
					{ title: 'Wartburg' },
					{ title: 'ZX' },
					{ title: 'Богдан' },
					{ title: 'ВАЗ' },
					{ title: 'ГАЗ' },
					{ title: 'ЗАЗ' },
					{ title: 'ИЖ' },
					{ title: 'ЛуАЗ' },
					{ title: 'Москвич / АЗЛК' },
					{ title: 'РАФ' },
					{ title: 'УАЗ' },
					{ title: 'Інші' },
				],
			},
			{
				title: 'Мото',
				link: '/motorcycles',
				subcategories: [
					{ title: 'Мотоцикли' },
					{ title: 'Мопеди / скутери' },
					{ title: 'Квадроцикли' },
					{ title: 'Електросамокати / гіроскутери' },
					{ title: 'Електроскутери' },
					{ title: 'Максі-скутер' },
					{ title: 'Електромотоцикли' },
					{ title: 'Електроквадрацикли' },
					{ title: 'Баггі' },
					{ title: 'Картинг' },
					{ title: 'Снігохід' },
					{ title: 'Мото - інше' },
				],
			},
			{
				title: 'Інший транспорт',
				link: '/other',
				subcategories: [
					{ title: 'Літаки' },
					{ title: 'Гелікоптери' },
					{ title: 'Дельтаплани' },
					{ title: 'Карети' },
					{ title: 'Залізничні тепловози' },
					{ title: 'Залізничні вагони' },
					{ title: 'Інші види транспорту' },
				],
			},
			{
				title: 'Вантажні автомобілі',
				link: '/trucks',
			},
			{
				title: 'Автобуси',
				link: '/buses',
			},
			{
				title: 'Водний транспорт',
				link: '/water-transport',
				subcategories: [
					{ title: 'Яхта' },
					{ title: 'Катер' },
					{ title: 'Моторний човен' },
					{ title: 'Катамаран' },
					{ title: 'Гребний човен' },
					{ title: 'Гідроцикл' },
					{ title: 'Каяк' },
					{ title: 'Інший водний транспорт' },
				],
			},
			{
				title: 'Причепи / будинки на колесах',
				link: '/trailers',
				subcategories: [
					{ title: 'Легковий причіп' },
					{ title: 'Лафет' },
					{ title: 'Напівпричіп' },
					{ title: 'Бортовий напівпричіп' },
					{ title: 'Вантажний причіп' },
					{ title: 'Причіп контейнеровоз' },
					{ title: 'Причіп зерновоз' },
					{ title: 'Самоскид напівпричіп' },
					{ title: 'Трал' },
					{ title: 'Торговий причіп' },
					{ title: 'Тракторний причіп' },
					{ title: 'Причіп фургон' },
					{ title: 'Причепи цистерни' },
					{ title: 'Автодім' },
					{ title: 'Кемпінг' },
					{ title: 'Причіп дача' },
					{ title: 'Інші причепи' },
				],
			},
			{
				title: 'Спецтехніка',
				link: '/special-equipment',
				subcategories: [
					{ title: 'Бульдозери / трактори' },
					{ title: 'Комунальна техніка' },
					{ title: 'Навантажувачі' },
					{ title: 'Самоскиди' },
					{ title: 'Будівельна техніка' },
					{ title: 'Екскаватори' },
					{ title: 'Автовишки' },
					{ title: 'Мінінавантажувач' },
					{ title: 'Бетонозмішувачі (міксери)' },
					{ title: 'Бетононасоси' },
					{ title: 'Бурова установка' },
					{ title: 'Сміттєвоз' },
					{ title: 'Лісозаготівельна техніка' },
					{ title: 'Машина асенізатор (вакуумна)' },
					{ title: 'Автокрани та маніпулятори' },
					{ title: 'Автогрейдер' },
					{ title: 'Асфальтоукладач' },
					{ title: 'Дорожній каток' },
					{ title: 'Всюдиходи' },
					{ title: 'Обладнання для спецтехніки' },
					{ title: 'Інша спецтехніка' },
				],
			},
			{
				title: 'Сільгосптехніка',
				link: '/agricultural-equipment',
				subcategories: [
					{ title: 'Трактор сільськогосподарський' },
					{ title: 'Мотоблок' },
					{ title: 'Мотокультиватор' },
					{ title: 'Міні-трактор' },
					{ title: 'Комбайн' },
					{ title: 'Навісне та додаткове обладнання' },
					{ title: 'Інша сільгосптехніка' },
					{ title: 'Інші' },
				],
			},
			{
				title: 'Автомобілі з Польщі',
				link: '/polish-cars',
			},
			{
				title: 'Вантажівки та спецтехніка з Польщі',
				link: '/polish-trucks',
			},
		],
	},
	{
		title: 'Запчастини для транспорту',
		img: 'category/parts.png',
		color: '#fff6d9',
		link: '/parts',
		subcategories: [
			{
				title: 'Шини, диски і колеса',
				link: '/tires_wheels',
				subcategories: [
					{ title: 'Автошини' },
					{ title: 'Диски' },
					{ title: 'Колеса в зборі' },
					{ title: 'Ковпаки' },
					{ title: 'Мотошини' },
					{ title: 'Мото диски та колеса' },
				],
			},
			{
				title: 'Запчастини для іншої техніки',
				link: '/other',
				subcategories: [
					{ title: 'Для вантажівок' },
					{ title: 'Для автобусів' },
					{ title: 'Для сільгосптехніки' },
					{ title: 'Для спецтехніки' },
					{ title: 'Для водного транспорту' },
					{ title: 'Для інших видів техніки' },
				],
			},
			{
				title: 'Мотозапчастини',
				link: '/motorcycle-parts',
				subcategories: [
					{
						title: 'Акумулятори',
						subcategories: [
							{ title: 'Для скутерів' },
							{ title: 'Для мотоциклів' },
							{ title: 'Для мопедів' },
							{ title: 'Інші' },
						],
					},
					{
						title: 'Амортизатори та підвіска',
						subcategories: [
							{ title: 'Задні амортизатори' },
							{ title: 'Передні амортизатори' },
							{ title: 'Сайлентблоки' },
							{ title: 'Сальники, пильовики амортизатора' },
							{ title: 'Траверси' },
							{ title: 'Інші' },
						],
					},
					{ title: 'Варіатори та редуктори' },
					{ title: 'Вихлопні системи, прямоструми, глушники' },
					{ title: 'Запчастини двигуна' },
					{ title: 'Коробка передач' },
					{ title: 'Ніжки та педалі' },
					{ title: 'Освітлення та лампи' },
					{ title: 'Підшипники' },
					{ title: 'Привід та ходова' },
					{ title: 'Рама, кронштейни та маятники' },
					{
						title: 'Кермо та управління',
						subcategories: [
							{ title: 'Кермо' },
							{ title: 'Рукоятки та гріпси' },
							{ title: 'Кермові демпфери' },
							{ title: 'Важелі' },
							{ title: 'Інші' },
						],
					},
					{ title: 'Сидіння' },
					{ title: 'Система охолодження' },
					{ title: 'Зчеплення' },
					{
						title: 'Паливна система',
						subcategories: [
							{ title: 'Бензобаки, кришки, датчики' },
							{ title: 'Карбюратори' },
							{ title: 'Інші' },
						],
					},
					{ title: 'Гальмівна система' },
					{ title: 'Троси та шланги' },
					{
						title: 'Фільтри',
						subcategories: [
							{ title: 'Повітряні' },
							{ title: 'Мастильні' },
							{ title: 'Паливні' },
							{ title: 'Інші' },
						],
					},
					{ title: 'Ланцюги та зірочки' },
					{
						title: 'Електрика',
						subcategories: [
							{ title: 'Генератори та магнето' },
							{ title: 'Замки запалювання' },
							{ title: 'Котушки запалювання' },
							{ title: 'Комутатори' },
							{ title: 'Реле' },
							{ title: 'Свічки запалювання' },
							{ title: 'Стартери' },
							{ title: 'Інші' },
						],
					},
					{ title: 'Інші мотозапчастини' },
				],
			},
			{
				title: 'Мотоекіпірування',
				link: '/motorcycle-gear',
				subcategories: [
					{ title: 'Мотошоломи' },
					{ title: 'Мотокуртки' },
					{ title: 'Мотоштани' },
					{ title: 'Мотоботи, моточеревики' },
					{ title: 'Мотокомбінезони' },
					{ title: 'Моторукавички' },
					{ title: 'Мотодощовики, мотобахіли' },
					{ title: 'Мотозахист' },
					{ title: 'Підшоломники' },
					{ title: 'Інше мотоекіпірування' },
				],
			},
			{
				title: 'Мотоаксесуари',
				link: '/motorcycle-accessories',
				subcategories: [
					{ title: 'Бризковики' },
					{ title: 'Тримач для телефона, планшета' },
					{ title: 'Інструменти' },
					{ title: 'Кріплення для номерів на мотоцикл' },
					{ title: 'Дзеркала на мотоцикл' },
					{ title: 'Наклейки на мотоцикл, скутер' },
					{ title: 'Обтічники та вітрове скло' },
					{ title: 'Відбійники (крашпеди)' },
					{ title: 'Панельні прилади' },
					{ title: 'Переговорні пристрої' },
					{ title: 'Підніжки' },
					{ title: 'Протиугінні системи' },
					{ title: 'Стайлінг' },
					{ title: 'Стенди та підйомники' },
					{ title: 'Чохли та накидки для мотоцикла' },
					{ title: 'Мотосумки, кофри, рюкзаки' },
					{ title: 'Інші мотоаксесуари' },
				],
			},
			{
				title: 'Аксесуари для авто',
				link: '/car-accessories',
				subcategories: [
					{ title: 'Авто інструменти, набори ключів' },
					{ title: 'Автоковрики' },
					{ title: 'Автомобільний органайзер' },
					{ title: 'Автонасоси, компресори, манометри' },
					{ title: 'Автоподушки' },
					{ title: 'Автосигналізації, блокувачі' },
					{ title: 'Автохолодильники' },
					{ title: 'Автошторки' },
					{ title: 'Ароматизатори, озонатори' },
					{ title: 'Багажники' },
					{ title: 'Бризковики' },
					{ title: 'Вентилятор в авто' },
					{ title: 'Вогнегасник, аптечка, аварійка' },
					{ title: 'Декоративна підсвітка авто' },
					{ title: 'Для тюнінгу' },
					{ title: 'Дефлектори' },
					{ title: 'Домкрати' },
					{ title: 'Елементи кріплення' },
					{ title: 'Каністри' },
					{ title: 'Ланцюги, браслети протиковзання' },
					{ title: 'Лебідки' },
					{ title: 'Наклейки, емблеми, значки' },
					{ title: 'Насадки на глушник' },
					{ title: 'Підігрів сидінь та автомасажери' },
					{ title: 'Підставки та тримачі' },
					{ title: 'Повітрозабірники' },
					{ title: 'Пороги та накладки' },
					{ title: 'Пускові та зарядні пристрої' },
					{ title: 'Рамки номерного знаку' },
					{ title: 'Салонний годинник, прилади, БК' },
					{ title: 'Тонування та сонцезахист' },
					{ title: 'Фаркопи' },
					{ title: 'Чохли, тенти, накидки' },
					{ title: 'Шумоізоляція' },
					{ title: 'Щітки та скребки' },
					{ title: 'Інші автоаксесуари' },
				],
			},
			{
				title: 'Автозвук та мультимедіа',
				link: '/car-audio',
				subcategories: [
					{
						title: 'Автомагнітоли',
						subcategories: [
							{ title: 'Alpine' },
							{ title: 'Pioneer' },
							{ title: 'Blaupunkt' },
							{ title: 'Clarion' },
							{ title: 'Sony' },
							{ title: 'Cyclon' },
							{ title: 'Incar' },
							{ title: 'JVC' },
							{ title: 'Kenwood' },
							{ title: 'LG' },
							{ title: 'Mystery' },
							{ title: 'Philips' },
							{ title: 'Prology' },
							{ title: 'SHUTTLE' },
							{ title: 'Swat' },
							{ title: 'Магнітоли інших марок' },
						],
					},
					{
						title: 'Колонки / сабвуфери',
						subcategories: [
							{ title: 'Alpine' },
							{ title: 'Blaupunkt' },
							{ title: 'DLS' },
							{ title: 'Edge' },
							{ title: 'Focal' },
							{ title: 'Hertz' },
							{ title: 'JBL' },
							{ title: 'JVC' },
							{ title: 'Kenwood' },
							{ title: 'Kicx' },
							{ title: 'Mystery' },
							{ title: 'Pioneer' },
							{ title: 'Sony' },
							{ title: 'Supra' },
							{ title: 'Колонки/сабвуфери інших марок' },
						],
					},
					{
						title: 'Підсилювачі',
						subcategories: [
							{ title: 'Alpine' },
							{ title: 'Blaupunkt' },
							{ title: 'DLS' },
							{ title: 'Ground Zero' },
							{ title: 'Hertz' },
							{ title: 'JBL' },
							{ title: 'JVC' },
							{ title: 'Kenwood' },
							{ title: 'Kicx' },
							{ title: 'Magnat' },
							{ title: 'Mystery' },
							{ title: 'Pioneer' },
							{ title: 'Pride' },
							{ title: 'Sony' },
							{ title: 'Supra' },
							{ title: 'Підсилювачі інших марок' },
						],
					},
					{ title: 'Антени для авто' },
					{ title: 'FM-трансмітери' },
					{ title: 'Кабелі, адаптери, запобіжники' },
					{ title: 'DVD, TV, інша мультимедіа' },
					{ title: 'Інші компоненти' },
				],
			},
			{
				title: 'GPS-навігатори / відеореєстратори',
				link: '/gps_dashcams',
				subcategories: [
					{ title: 'GPS-навігатори' },
					{ title: 'Навігаційні карти та GPS-аксесуари' },
					{ title: 'Відеореєстратори' },
				],
			},
			{
				title: 'Транспорт на запчастини / авторозбірки',
				link: '/parts_transport',
				subcategories: [
					{ title: 'Acura' },
					{ title: 'Audi' },
					{ title: 'BMW' },
					{ title: 'Chevrolet' },
					{ title: 'Chrysler' },
					{ title: 'Citroen' },
					{ title: 'Daewoo' },
					{ title: 'Dodge' },
					{ title: 'Fiat' },
					{ title: 'Ford' },
					{ title: 'Honda' },
					{ title: 'Hyundai' },
					{ title: 'Infiniti' },
					{ title: 'Jeep' },
					{ title: 'Kia' },
					{ title: 'Land Rover' },
					{ title: 'Lexus' },
					{ title: 'Lincoln' },
					{ title: 'Mazda' },
					{ title: 'Mercedes-Benz' },
					{ title: 'Mitsubishi' },
					{ title: 'Nissan' },
					{ title: 'Opel' },
					{ title: 'Peugeot' },
					{ title: 'Porsche' },
					{ title: 'Renault' },
					{ title: 'Rover' },
					{ title: 'Seat' },
					{ title: 'Skoda' },
					{ title: 'Subaru' },
					{ title: 'Suzuki' },
					{ title: 'Toyota' },
					{ title: 'Volkswagen' },
					{ title: 'Volvo' },
					{ title: 'ВАЗ' },
					{ title: 'ГАЗ' },
					{ title: 'ЗАЗ' },
					{ title: 'ИЖ' },
					{ title: 'Москвич' },
					{ title: 'Інший бренд' },
				],
			},
			{
				title: 'Автозапчастини',
				link: '/car-parts',
				subcategories: [
					{
						title: 'Двигун',
						subcategories: [
							{ title: 'Блок циліндрів та його частини' },
							{ title: 'Газорозподільний механізм (ГРМ)' },
							{ title: 'Двигуни у зборі' },
							{ title: 'Кожухи та кришки двигуна' },
							{ title: 'Кривошипно-шатунний механізм' },
							{ title: 'Маховики та їхні компоненти' },
							{ title: 'Подушки двигуна' },
							{ title: 'Підшипники двигуна' },
							{ title: 'Поршнева група' },
							{ title: 'Прокладки та комплекти прокладок' },
							{ title: 'Ролики та натягувачі' },
							{ title: 'Радіатори автомобільні' },
							{ title: 'Сальники та ущільнюючі кільця' },
							{ title: 'Система змащування двигуна' },
							{ title: 'Турбіни, турбокомпресори' },
							{ title: 'Шківи та шпонки двигуна' },
							{ title: 'Інші запчастини двигуна' },
						],
					},
					{
						title: 'Вихлопна система',
						subcategories: [
							{ title: 'Вихлопні колектори' },
							{ title: 'Вихлопні системи в зборі' },
							{ title: 'Глушники' },
							{ title: 'Гофри' },
							{ title: 'Датчики кисневі (лямбда-зонд)' },
							{ title: 'Датчики температури палива, оливи та інші' },
							{ title: 'Каталізатори' },
							{ title: 'Клапани EGR' },
							{ title: "Полум'ягасники" },
							{ title: 'Резонатори' },
							{ title: 'Труби та частини вихлопної системи' },
							{ title: 'Інші запчастини вихлопної системи' },
						],
					},
					{
						title: 'Трансмісія / КПП та АКПП',
						subcategories: [
							{ title: 'Карданні вали' },
							{ title: 'Приводні вали' },
							{ title: 'Варіатор' },
							{ title: 'Вилки та штоки перемикання передач' },
							{ title: 'Гідротрансформатор' },
							{ title: 'Диски фрикційні та віскомуфти' },
							{ title: 'Диференціали (редуктори)' },
							{ title: 'Компоненти КПП / АКПП' },
							{ title: 'Коробки відбору потужності' },
							{ title: 'КПП / АКПП у зборі' },
							{ title: 'Мости трансмісії' },
							{ title: 'Муфти еластичні' },
							{ title: 'Підшипники трансмісії' },
							{ title: 'Циліндри зчеплення' },
							{ title: 'Шруси' },
							{ title: 'Інші запчастини трансмісії' },
						],
					},
					{
						title: 'Кермове управління',
						subcategories: [
							{ title: 'Керма та їхні компоненти' },
							{ title: 'Амортизатори та стабілізатори рульового керування' },
							{ title: 'Кермові вали та їхні компоненти' },
							{ title: 'Гідропідсилювач керма' },
							{ title: 'Накінечники кермові' },
							{ title: 'Педаль газу' },
							{ title: 'Пильовики, відбійники' },
							{ title: 'Рейки кермового управління' },
							{ title: 'Кермові механізми' },
							{ title: 'Кермові тяги' },
							{ title: 'Інші запчастини системи керування' },
						],
					},
					{
						title: 'Ходова частина / підвіска',
						subcategories: [
							{ title: 'Амортизатори' },
							{ title: 'Балки підвіски' },
							{ title: 'Втулки' },
							{ title: 'Кульові опори' },
							{ title: 'Пневморесори, пневмоподушки' },
							{ title: 'Поворотні кулаки' },
							{ title: 'Проставки для збільшення кліренсу' },
							{ title: 'Пружини підвіски' },
							{ title: 'Ресори та їхні складові' },
							{ title: 'Важелі, тяги' },
							{ title: 'Сайлентблоки' },
							{ title: 'Стійки стабілізаторів' },
							{ title: 'Маточини, підшипники маточини' },
							{ title: 'Торсіони' },
							{ title: 'Інші запчастини підвіски' },
						],
					},
					{
						title: 'Паливна система',
						subcategories: [
							{ title: 'Паливні насоси' },
							{ title: 'Баки та бачки паливної системи' },
							{ title: 'Впускні колектори' },
							{ title: 'Дросельні заслінки' },
							{ title: 'Карбюратори та комплектуючі' },
							{ title: 'Розпилювачі та паливні форсунки' },
							{ title: 'Регулятори тиску палива' },
							{ title: 'Інші запчастини паливної системи' },
						],
					},
					{
						title: 'Гальмівна система',
						subcategories: [
							{ title: 'Барабани гальмівні' },
							{ title: 'Деталі гальмівних систем ABS, EBD' },
							{ title: 'Гальмівні камери та енергоакумулятори' },
							{ title: 'Накладки гальмівні' },
							{ title: 'Ресивери' },
							{ title: 'Ретардери' },
							{ title: 'Гальмівні диски' },
							{ title: 'Гальмівні колодки дискові' },
							{ title: 'Гальмівні колодки барабанні' },
							{ title: 'Гальмівні супорти' },
							{ title: 'Гальмівні циліндри' },
							{ title: 'Гальмівні шланги' },
							{ title: 'Підсилювачі гальм та їхні компоненти' },
							{ title: 'Інші запчастини гальмівної системи' },
						],
					},
					{
						title: 'Кузовні запчастини',
						subcategories: [
							{ title: 'Багажники, задні панелі та їхні деталі' },
							{ title: 'Бампери' },
							{ title: 'Підсилювачі бампера, буфер бампера' },
							{ title: 'Двері' },
							{ title: 'Захист картера та КПП' },
							{ title: 'Капоти та їхні частини' },
							{ title: 'Амортизатори капота, багажника' },
							{ title: 'Крила та їхні частини' },
							{ title: 'Кузови легкових автомобілів' },
							{ title: 'Дверні замки та ключі' },
							{ title: 'Автомобільні люки' },
							{ title: 'Лонжерони, підрамники' },
							{ title: 'Лючки, кришки бензобака' },
							{ title: 'Нижня частина кузова та рама автомобіля' },
							{ title: 'Передня панель, телевізор' },
							{ title: 'Решітка радіатора' },
							{ title: 'Інші кузовні запчастини' },
						],
					},
					{
						title: 'Деталі салону',
						subcategories: [
							{ title: 'Автосидіння, крісла' },
							{ title: 'Бардачки' },
							{ title: 'Дверні карти, обшивка дверей' },
							{ title: 'Дзеркала' },
							{ title: 'Задня полиця' },
							{ title: 'Кнопки / Перемикачі' },
							{ title: 'Матеріал для підлоги' },
							{ title: 'Попільничка' },
							{ title: 'Пластик салону' },
							{ title: 'Підлокітник' },
							{ title: 'Підсклянник' },
							{ title: 'Подушки безпеки, AIRBAG' },
							{ title: 'Прикурювач' },
							{ title: 'Ремені безпеки та натягувач' },
							{ title: 'Кермо' },
							{ title: 'Ручки дверей та салону' },
							{ title: 'Ручки КПП' },
							{ title: 'Торпедо, консоль' },
							{ title: 'Інші деталі салону' },
						],
					},
					{
						title: 'Кондиціонер, обігрівач, вентиляція',
						subcategories: [
							{ title: 'Автомобільні кондиціонери у зборі' },
							{ title: 'Автономні обігрівачі' },
							{ title: 'Блок управління кондиціонером' },
							{ title: 'Вентилятори, системи кондиціювання та опалення' },
							{ title: 'Випарники' },
							{ title: 'Компресори' },
							{ title: 'Конденсатори кондиціонера' },
							{ title: 'Радіатори обігрівачів' },
							{ title: 'Трубки, шланги, повітропроводи' },
							{ title: 'Інші запчастини кондиціонерів та опалення' },
						],
					},
					{
						title: 'Система подачі повітря',
						subcategories: [
							{ title: 'Впускний та випускний колектори' },
							{ title: 'Інтеркулери' },
							{ title: 'Корпуси повітряного фільтра' },
							{ title: 'Патрубки турбіни та інтеркулера' },
							{ title: 'Інші запчастини подачі повітря' },
						],
					},
					{
						title: 'Система запалювання',
						subcategories: [
							{ title: 'Високовольтні дроти запалювання' },
							{ title: 'Замки запалювання та ключі' },
							{ title: 'Котушки запалювання' },
							{ title: 'Свічки запалювання' },
							{ title: 'Свічки розжарювання' },
							{ title: 'Стартер, запчастини стартера' },
							{ title: 'Трамблери' },
							{ title: 'Інші запчастини системи запалення' },
						],
					},
					{
						title: 'Система очищення вікон та фар',
						subcategories: [
							{ title: 'Бачки та кришки омивачів' },
							{ title: 'Моторчики двірників' },
							{ title: 'Насоси омивача' },
							{ title: 'Гумки для склоочисників' },
							{ title: 'Форсунки омивача' },
							{ title: 'Двірники' },
							{ title: 'Інші запчастини очищення вікон та фар' },
						],
					},
					{
						title: 'Фари та освітлення',
						subcategories: [
							{ title: 'Передні фари' },
							{ title: 'Задні фари' },
							{ title: 'Протитуманні фари' },
							{ title: 'Денні ходові вогні' },
							{ title: 'Ксенон' },
							{ title: 'Лампочки' },
							{ title: 'Відбивачі, корпуси фар' },
							{ title: 'Повторювачі поворотів' },
							{ title: "Освітлення інтер'єру" },
							{ title: 'Інші елементи освітлення' },
						],
					},
					{
						title: 'Електрообладнання',
						subcategories: [
							{ title: 'Акумулятори' },
							{ title: 'Блоки керування' },
							{ title: 'Генератор, запчастини генератора' },
							{ title: 'Кнопки та вимикачі' },
							{ title: 'Панелі приладів' },
							{ title: 'Запобіжники, переривники' },
							{ title: 'Прикурювачі та комплектуючі' },
							{ title: 'Реле' },
							{ title: 'Звукові сигнали' },
							{ title: 'Електропроводка та компоненти' },
							{ title: 'Інше електрообладнання' },
						],
					},
					{
						title: 'Фільтри',
						subcategories: [
							{ title: 'Повітряні фільтри' },
							{ title: 'Мастильні фільтри' },
							{ title: 'Паливні фільтри' },
							{ title: 'Фільтри салону' },
							{ title: 'Фільтри ГБО' },
							{ title: 'Фільтри інших типів' },
						],
					},
					{
						title: 'Автоскло',
						subcategories: [
							{ title: 'Скло вітрове (лобове)' },
							{ title: 'Бічне скло' },
							{ title: 'Скло дверей' },
							{ title: 'Заднє скло' },
							{ title: 'Автоскло інших видів' },
						],
					},
					{
						title: 'ГБО',
						subcategories: [
							{ title: 'Балони газові' },
							{ title: 'Редуктори газові' },
							{ title: 'Форсунки газові' },
							{ title: 'Інші компоненти ГБО' },
						],
					},
					{ title: 'Інші види запчастин' },
				],
			},
			{
				title: 'Мастила та автохімія',
				link: '/oils_chemicals',
				subcategories: [
					{ title: 'Моторні мастила' },
					{ title: 'Трансмісійні мастила' },
					{ title: 'Гідравлічні мастила' },
					{ title: 'Мастила для мототехніки' },
					{ title: 'Автокосметика та автохімія' },
					{ title: 'Інші мастила та рідини' },
				],
			},
		],
	},
	{
		title: 'Робота',
		img: 'category/work.png',
		link: '/work',
		color: '#ceddff',
		subcategories: [
			{
				title: 'Медицина / фармацевтика',
				link: '/medicine_pharmaceuticals',
				subcategories: [
					{ title: 'Медсестра' },
					{ title: 'Стоматолог' },
					{ title: 'Фармацевт' },
					{ title: 'Інше' },
				],
			},
			{
				title: 'Часткова зайнятість',
				link: '/part-time',
			},
			{
				title: 'Краса / фітнес / спорт',
				link: '/beauty_fitness_sports',
				subcategories: [
					{ title: 'Перукар' },
					{ title: 'Майстер манікюру' },
					{ title: 'Адміністратор' },
					{ title: 'Масажист' },
					{ title: 'Косметолог' },
					{ title: 'Тренер' },
					{ title: 'Інше' },
				],
			},
			{
				title: 'Логістика / Склад / Доставка',
				link: '/logistics_warehouse_delivery',
				subcategories: [
					{ title: 'Водій' },
					{ title: 'Вантажник' },
					{ title: "Кур'єр" },
					{ title: 'Комірник' },
					{ title: 'Диспетчер' },
					{ title: 'Експедитор' },
					{ title: 'Далекобійник' },
					{ title: 'Таксист' },
					{ title: 'Інше' },
				],
			},
			{
				title: 'Освіта / переклад',
				link: '/education_translation',
				subcategories: [
					{ title: 'Викладач / Вчитель' },
					{ title: 'Вихователь' },
					{ title: 'Репетитор' },
					{ title: 'Інше' },
				],
			},
			{
				title: 'Виробництво / робітничі спеціальності',
				link: '/production_blue-collar-jobs',
				subcategories: [
					{ title: 'Електрик' },
					{ title: 'Столяр' },
					{ title: 'Швачка, кравець' },
					{ title: 'Токар' },
					{ title: 'Машиніст екскаватора' },
					{ title: 'Конструктор' },
					{ title: 'Комплектувальник' },
					{ title: 'Складальник меблів' },
					{ title: 'Різноробочий' },
					{ title: 'Зварювальник' },
					{ title: 'Складальник' },
					{ title: 'Слюсар' },
					{ title: 'Маляр' },
					{ title: 'Пакувальник' },
					{ title: 'Монтажник' },
					{ title: 'Механік' },
					{ title: 'Підсобник' },
					{ title: 'Оператор ЧПУ' },
					{ title: 'Технолог' },
					{ title: 'Інше' },
				],
			},
			{
				title: 'Роздрібна торгівля / продажі / закупки',
				link: '/retail_sales_purchasing',
				subcategories: [
					{ title: 'Мерчендайзер' },
					{ title: 'Менеджер з продажу' },
					{ title: 'Продавець' },
					{ title: 'Супервайзер' },
					{ title: 'Флорист' },
					{ title: 'Продавець-консультант' },
					{ title: 'Торговий представник' },
					{ title: 'Менеджер інтернет-магазину' },
					{ title: 'Касир' },
					{ title: 'Менеджер по роботі з клієнтами' },
					{ title: 'Товарознавець' },
					{ title: 'Керівник відділу продажів' },
					{ title: 'Менеджер по закупці' },
					{ title: 'Адміністратор' },
					{ title: 'Пекар' },
					{ title: 'Інше' },
				],
			},
			{
				title: 'Реклама / дизайн / PR',
				link: '/advertising_design_pr',
				subcategories: [
					{ title: 'Промоутер' },
					{ title: 'Дизайнер' },
					{ title: 'Маркетолог' },
					{ title: 'SMM-менеджер' },
					{ title: 'Контент-менеджер' },
					{ title: 'Копірайтер' },
					{ title: 'Інше' },
				],
			},
			{
				title: "IT / комп'ютери",
				link: '/it_computers',
				subcategories: [
					{ title: 'Оператор ПК' },
					{ title: 'Майстер з ремонту' },
					{ title: 'Системний адміністратор' },
					{ title: 'Інше' },
				],
			},
			{
				title: 'Будівництво / облицювальні роботи',
				link: '/construction_finishing_works',
				subcategories: [
					{ title: 'Різноробочий' },
					{ title: 'Муляр' },
					{ title: 'Плиточник' },
					{ title: 'Монтажник' },
					{ title: 'Зварювальник' },
					{ title: 'Будівельник' },
					{ title: 'Маляр' },
					{ title: 'Виконроб' },
					{ title: 'Сантехнік' },
					{ title: 'Фасадник' },
					{ title: 'Штукатур' },
					{ title: 'Електрик' },
					{ title: 'Інше' },
				],
			},
			{
				title: 'Інші сфери занять',
				link: '/other',
			},
			{
				title: 'Охорона / безпека',
				link: '/security_safety',
				subcategories: [
					{ title: 'Охоронець' },
					{ title: 'Сторож' },
					{ title: 'Інше' },
				],
			},
			{
				title: 'Культура / мистецтво / розваги',
				link: '/culture_art_entertainment',
				subcategories: [
					{ title: 'Фотограф' },
					{ title: 'Модель' },
					{ title: 'Аніматор' },
					{ title: 'Інше' },
				],
			},
			{
				title: 'Клінінг / Домашній персонал',
				link: '/cleaning_domestic',
				subcategories: [
					{ title: 'Доглядальниця' },
					{ title: 'Прибиральниця' },
					{ title: 'Двірник' },
					{ title: 'Няня' },
					{ title: 'Домробітниця' },
					{ title: 'Інше' },
				],
			},
			{
				title: 'Нерухомість',
				link: '/real-estate',
				subcategories: [
					{ title: 'Ріелтор' },
					{ title: 'Менеджер з продажу' },
					{ title: 'Брокер' },
					{ title: 'Інше' },
				],
			},
			{
				title: "Початок кар'єри / Студенти",
				link: '/career-start_students',
			},
			{
				title: 'Адміністративний персонал / HR / Секретаріат',
				link: '/administrative_hr_secretarial',
				subcategories: [
					{ title: 'Адміністратор' },
					{ title: 'Секретар' },
					{ title: 'Офіс менеджер' },
					{ title: 'HR' },
					{ title: 'Інше' },
				],
			},
			{
				title: 'Банки / фінанси / страхування / юриспруденція',
				link: '/banking_finance_insurance_law',
				subcategories: [{ title: 'Юрист' }, { title: 'Інше' }],
			},
			{
				title: 'Колл-центри / Телекомунікації',
				link: '/call-centers_telecommunications',
				subcategories: [
					{ title: 'Оператор колл-центру' },
					{ title: 'Оператор чату' },
					{ title: 'Інше' },
				],
			},
			{
				title: 'Сільське і лісове господарство / агробізнес',
				link: '/agriculture-forestry_agribusiness',
				subcategories: [
					{ title: 'Агроном' },
					{ title: 'Тракторист' },
					{ title: 'Пилорамщик' },
					{ title: 'Інше' },
				],
			},
			{
				title: 'Робота за кордоном',
				link: '/work-abroad',
				subcategories: [
					{ title: 'Різноробочий' },
					{ title: 'Кухар' },
					{ title: 'Водій' },
					{ title: 'Няня' },
					{ title: 'Доглядальниця' },
					{ title: 'Зварювальник' },
					{ title: 'Будівельник' },
					{ title: 'Пакувальник' },
					{ title: 'Інше' },
				],
			},
			{
				title: 'Бухгалтерія',
				link: '/accounting',
				subcategories: [
					{ title: 'Бухгалтер' },
					{ title: 'Аудитор' },
					{ title: 'Інше' },
				],
			},
			{
				title: 'Готельно-ресторанний бізнес / Туризм',
				link: '/hotel-restaurant-business_tourism',
				subcategories: [
					{ title: 'Адміністратор' },
					{ title: 'Покоївка' },
					{ title: 'Менеджер' },
					{ title: 'Бариста' },
					{ title: 'Кухар' },
					{ title: 'Бармен' },
					{ title: 'Офіціант' },
					{ title: 'Кондитер' },
					{ title: 'Пекар' },
					{ title: 'Помічник кухаря' },
					{ title: 'Сушист' },
					{ title: 'Посудомийниця' },
					{ title: 'Піцайоло' },
					{ title: 'Інше' },
				],
			},
			{
				title: 'СТО / автомийки',
				link: '/auto-service_car-washes',
				subcategories: [
					{ title: 'Автослюсар' },
					{ title: 'Мийник' },
					{ title: 'Механік' },
					{ title: 'Автомаляр' },
					{ title: 'Автоелектрик' },
					{ title: 'Рихтувальник' },
					{ title: 'Шиномонтажник' },
					{ title: 'Інше' },
				],
			},
			{
				title: 'Служба в Силах оборони',
				link: '/military-service',
			},
			{
				title: 'Робота швачкою',
				link: '/seamstress',
			},
		],
	},
	{
		title: 'Тварини',
		img: 'category/pets.png',
		color: '#c8f8f6',
		link: '/animals',
		subcategories: [
			{
				title: 'Собаки',
				link: '/dogs',
			},
			{
				title: 'Коти',
				link: '/cats',
			},
			{
				title: 'Інші тварини',
				link: '/other',
			},
			{
				title: 'Зоотовари',
				link: '/pet-supplies',
			},
			{
				title: 'Бюро знахідок',
				link: '/lost-and-found',
			},
			{
				title: "В'язка",
				link: '/breeding',
			},
			{
				title: 'Пташки',
				link: '/birds',
			},
			{
				title: 'Гризуни',
				link: '/rodents',
			},
			{
				title: 'Рептилії',
				link: '/reptiles',
			},
			{
				title: 'Акваріумістика',
				link: '/aquariums',
			},
			{
				title: 'Сільгосп тварини',
				link: '/farm-animals',
			},
			{
				title: "Безкоштовно (тварини і в'язка)",
				link: '/free-animals-breeding',
			},
		],
	},
	{
		title: 'Дім і сад',
		link: '/household',
		img: 'category/household.png',
		color: '#ffd6c9',
		subcategories: [
			{
				title: 'Кімнатні рослини',
				link: '/indoor-plants',
			},
			{
				title: 'Меблі',
				link: '/furniture',
				subcategories: [
					{ title: 'Меблі для вітальні' },
					{ title: 'Меблі для спальні' },
					{ title: 'Меблі для передпокою' },
					{ title: 'Кухонні меблі' },
					{ title: 'Меблі для ванної кімнати' },
					{ title: 'Офісні меблі' },
					{ title: 'Меблі на замовлення' },
				],
			},
			{
				title: "Предмети інтер'єру",
				link: '/interior-items',
				subcategories: [
					{ title: 'Освітлення' },
					{ title: 'Текстиль' },
					{ title: 'Декор вікон' },
				],
			},
			{
				title: 'Інші товари для дому',
				link: '/other',
			},
			{
				title: 'Продукти харчування / напої',
				link: '/food_beverages',
			},
			{
				title: 'Господарський інвентар / побутова хімія',
				link: '/household-inventory_chemicals',
			},
			{
				title: 'Садовий інвентар',
				link: '/garden-inventory',
			},
			{
				title: 'Канцтовари / витратні матеріали',
				link: '/stationery_consumables',
			},
			{
				title: 'Будівництво / ремонт',
				link: '/construction_repair',
				subcategories: [
					{ title: 'Вентиляція' },
					{ title: 'Сантехніка' },
					{ title: 'Опалення' },
					{ title: 'Електрика' },
					{ title: 'Пиломатеріали' },
					{ title: 'Оздоблювальні та облицювальні матеріали' },
					{ title: 'Вікна / двері / скло / дзеркала' },
					{ title: 'Лакофарбові матеріали' },
					{ title: 'Металопрокат / арматура' },
					{ title: 'Елементи кріплення' },
					{ title: 'Цегла / бетон / піноблоки' },
					{ title: 'Інші будматеріали' },
				],
			},
			{
				title: 'Інструменти',
				link: '/tools',
				subcategories: [
					{ title: 'Генератори' },
					{ title: 'Ручний інструмент' },
					{ title: 'Електроінструмент' },
					{ title: 'Пневмоінструмент' },
					{ title: 'Інший інструмент' },
				],
			},
			{
				title: 'Посуд / кухонне приладдя',
				link: '/dishes_kitchenware',
			},
			{
				title: 'Сад / город',
				link: '/garden',
			},
		],
	},
	{
		title: 'Електроніка',
		link: '/electronics',
		img: 'category/electronic.png',
		color: '#ffce32',
		subcategories: [
			{
				title: "Комп'ютери та комплектуючі",
				link: '/computers_components',
				subcategories: [
					{ title: "Настільні комп'ютери" },
					{ title: 'Сервери' },
					{ title: 'Комплектуючі та аксесуари' },
					{ title: 'Периферійні пристрої' },
					{ title: 'Монітори' },
					{ title: 'Зовнішні накопичувачі' },
					{ title: 'Витратні матеріали' },
					{ title: 'Інше' },
				],
			},
			{
				title: 'Телефони та аксесуари',
				link: '/phones_accessories',
				subcategories: [
					{
						title: 'Запчастини для телефонів',
					},
					{
						title: 'Аксесуари для телефонів',
						subcategories: [
							{ title: 'PowerBank та акумулятори' },
							{ title: 'Зарядні пристрої та док-станції' },
							{ title: 'Гарнітури' },
							{ title: 'Корпуси / панелі' },
							{ title: 'Чохли' },
							{ title: 'Data-кабелі' },
							{ title: "Карти пам'яті" },
							{ title: 'Захисні плівки та скло' },
							{ title: 'Моноподи для селфі' },
							{ title: 'Окуляри віртуальної реальності' },
							{ title: 'Смарт годинники' },
							{ title: 'Фітнес-трекери' },
							{ title: 'Інші аксесуари для телефонів' },
						],
					},
					{
						title: 'Мобільні телефони / смартфони',
					},
					{
						title: 'Сім-карти / тарифи / номери',
					},
					{
						title: 'Стаціонарні телефони',
					},
					{
						title: 'Рації та інші телефони',
					},
				],
			},
			{
				title: 'Ігри та ігрові приставки',
				link: '/games_gaming-consoles',
				subcategories: [
					{ title: 'Ігри для приставок' },
					{ title: 'Приставки' },
					{ title: 'Ігри для PC' },
					{ title: 'Аксесуари' },
					{ title: 'Герої ігор' },
				],
			},
			{
				title: 'Техніка для кухні',
				link: '/kitchen-appliances',
				subcategories: [
					{ title: 'Мікрохвильові печі' },
					{ title: 'Холодильники' },
					{ title: 'Плити / печі' },
					{ title: 'Електрочайники' },
					{ title: 'Кавоварки / кавомолки' },
					{ title: 'Кухонні комбайни та подрібнювачі' },
					{ title: 'Пароварки, мультиварки' },
					{ title: 'Хлібопічки' },
					{ title: 'Посудомийні машини' },
					{ title: 'Витяжки' },
					{ title: 'Інша техніка для кухні' },
				],
			},
			{
				title: 'Техніка для дому',
				link: '/home-appliances',
				subcategories: [
					{ title: 'Пилососи' },
					{ title: 'Праски' },
					{ title: 'Пральні машини' },
					{ title: 'Швейні машини та оверлоки' },
					{ title: "В'язальні машини" },
					{ title: 'Фільтри для води' },
					{ title: 'Зарядні станції' },
					{ title: 'Перетворювачі напруги' },
					{ title: 'Безперебійники живлення' },
					{ title: 'Інша техніка для дому' },
				],
			},
			{
				title: 'Індивідуальний догляд',
				link: '/personal-care',
				subcategories: [
					{ title: 'Бритви, епілятори, машинки для стрижки' },
					{ title: 'Фени, укладка волосся' },
					{ title: 'Ваги' },
					{ title: 'Інша техніка для індивідуального догляду' },
				],
			},
			{
				title: 'Кліматичне обладнання',
				link: '/climate-equipment',
			},
			{
				title: 'Аксесуари й комплектуючі',
				link: '/accessories_components',
			},
			{
				title: 'Аудіотехніка',
				link: '/audio-equipment',
				subcategories: [
					{ title: 'Mp3 плеєри' },
					{ title: 'Магнітоли' },
					{ title: 'Музичні центри' },
					{ title: 'Акустичні системи' },
					{ title: 'Навушники' },
					{ title: 'Радіоприймачі' },
					{ title: 'Портативна акустика' },
					{ title: 'Підсилювачі / ресивери' },
					{ title: 'Cd / md / вінілові програвачі' },
					{ title: 'Інша аудіотехніка' },
				],
			},
			{
				title: 'Тв / відеотехніка',
				link: '/tv_video-equipment',
				subcategories: [
					{ title: 'Медіа програвачі' },
					{ title: 'Телевізори' },
					{ title: 'Проектори' },
					{ title: 'Аксесуари для ТВ/Відеотехніки' },
					{ title: 'Супутникове ТВ' },
					{ title: 'Інша ТВ / відеотехніка' },
				],
			},
			{
				title: 'Фото / відео',
				link: '/photo_video',
				subcategories: [
					{ title: 'Цифрові фотоапарати' },
					{ title: 'Відеокамери' },
					{ title: 'Екшн-камери' },
					{ title: "Об'єктиви" },
					{ title: 'Штативи / моноподи' },
					{ title: 'Фотоспалахи' },
					{ title: 'Аксесуари для фото / відеокамер' },
					{ title: 'Телескопи / біноклі' },
					{ title: 'Плівкові фотоапарати' },
				],
			},
			{
				title: 'Інша електроніка',
				link: '/other',
			},
			{
				title: 'Ноутбуки та аксесуари',
				link: '/laptops_accessories',
				subcategories: [
					{ title: 'Ноутбуки' },
					{ title: 'Запчастини для ноутбуків' },
					{ title: 'Аксесуари для ноутбуків' },
				],
			},
			{
				title: 'Планшети / ел. книги та аксесуари',
				link: '/tablets_ebooks_accessories',
				subcategories: [
					{ title: "Планшетні комп'ютери" },
					{ title: 'Електронні книги' },
					{ title: 'Графічні планшети' },
					{ title: 'Запчастини для планшетів / ел. книг' },
					{ title: 'Аксесуари для планшетів / ел. книг' },
				],
			},
			{
				title: 'Ремонт та обслуговування техніки',
				link: '/electronics_repair-maintenance',
			},
		],
	},
	{
		title: 'Бізнес та послуги',
		link: '/services',
		color: '#ceddff',
		img: 'category/services.png',
		subcategories: [
			{
				title: 'Продаж бізнесу',
				link: '/business-for-sale',
				subcategories: [
					{ title: 'Магазини' },
					{ title: 'Акаунти в соціальних мережах' },
					{ title: 'Підприємства, компанії' },
					{ title: "Кафе, ресторани, кав'ярні" },
					{ title: 'Франшизи' },
					{ title: 'Інтернет-магазини' },
					{ title: 'Інші види бізнесу' },
				],
			},
			{
				title: 'Продаж обладнання для бізнесу',
				link: '/business-equipment-for-sale',
				subcategories: [
					{ title: 'Торгово-виставкове обладнання' },
					{ title: 'Холодильне обладнання' },
					{ title: 'Розрахунково-касове обладнання' },
					{ title: 'Промислове обладнання' },
					{ title: 'Обладнання для ресторанів і кафе' },
					{ title: 'Лабораторне обладнання' },
					{ title: 'Медичне обладнання' },
					{ title: 'Обладнання для салонів краси' },
					{ title: 'Інше обладнання' },
				],
			},
			{
				title: 'Авто / мото послуги',
				link: '/auto_moto',
			},
			{
				title: 'Інші послуги',
				link: '/other',
			},
			{
				title: 'Будівництво та ремонт',
				link: '/construction_repair',
				subcategories: [
					{ title: 'Будівництво під ключ' },
					{ title: 'Ремонт під ключ' },
					{ title: 'Проєктування та дизайн' },
					{ title: 'Будівельні послуги' },
					{ title: 'Сантехніка та комунікації' },
					{ title: 'Оздоблення, ремонт' },
					{ title: 'Електромонтажні послуги' },
					{ title: 'Встановлення та ремонт систем безпеки' },
					{ title: 'Вентиляція та кондиціонування' },
					{ title: 'Монтаж вікон, дверей, балконів' },
					{ title: 'Зварювальні роботи' },
					{ title: 'Демонтажні роботи' },
					{ title: 'Готові конструкції' },
					{ title: 'Ландшафтні та земляні роботи' },
					{ title: 'Буріння свердловин' },
					{ title: 'Інші послуги з будівництва' },
				],
			},
			{
				title: 'Туризм / іміграція',
				link: '/tourism_immigration',
				subcategories: [
					{ title: 'Тури та екскурсії' },
					{ title: 'Оформлення віз' },
					{ title: 'Інші послуги туризму' },
				],
			},
			{
				title: 'Перевезення та послуги спецтехніки',
				link: '/transportation-special-equipment',
				subcategories: [
					{ title: 'Вантажоперевезення' },
					{ title: 'Пасажирські перевезення' },
					{ title: 'Послуги маніпулятора' },
					{ title: 'Послуги евакуатора, автовозу' },
					{ title: 'Послуги вантажників' },
					{ title: 'Послуги водіїв' },
					{ title: 'Інші транспортні послуги' },
				],
			},
			{
				title: "Краса / здоров'я",
				link: '/beauty_health',
				subcategories: [
					{ title: 'Перукарські послуги' },
					{ title: 'Манікюр, педикюр, нарощування' },
					{ title: 'Вії та брови' },
					{ title: 'Медичні послуги' },
					{ title: 'Масаж' },
					{ title: 'Послуги психолога' },
					{ title: 'Тату, татуаж, пірсинг' },
					{ title: 'Візаж та макіяж' },
					{ title: 'Косметологічні послуги' },
					{ title: 'Видалення волосся' },
					{ title: "Моделі для б'юті-послуг" },
					{ title: 'Лазні, сауни та СПА' },
					{ title: "Інші б'юті-послуги" },
				],
			},
			{
				title: 'Послуги для тварин',
				link: '/services-for-animals',
				subcategories: [
					{ title: 'Дресирування, кінологи, вигул' },
					{ title: 'Грумінг, стрижки, салони' },
					{ title: 'Перетримка тварин і готелі' },
					{ title: 'Ветеринарна допомога' },
					{ title: 'Інші послуги для тварин' },
				],
			},
			{
				title: 'Фото та відеозйомка',
				link: '/photo-video',
				subcategories: [
					{ title: 'Фотозйомка та ретуш фото' },
					{ title: 'Оцифрування та реставрація' },
					{ title: 'Відеозйомка та монтаж відео' },
					{ title: 'Інші фото та відео послуги' },
				],
			},
			{
				title: 'Послуги освіти та спорту',
				link: '/education-sports',
				subcategories: [
					{ title: 'Автоінструктори' },
					{ title: 'Дитячий розвиток, логопеди' },
					{ title: 'Репетитори' },
					{ title: 'Курси та тренінги' },
					{ title: 'Викладачі музики та вокалу' },
					{ title: 'Спорт і танці' },
					{ title: 'Інші послуги освіти' },
				],
			},
			{
				title: 'Догляд за дітьми та літніми людьми',
				link: '/care-for-children-elderly',
				subcategories: [{ title: 'Няня' }, { title: 'Доглядальниця' }],
			},
			{
				title: 'Сировина / матеріали',
				link: '/raw_materials',
				subcategories: [
					{ title: 'Паливо' },
					{ title: 'Дрова, вугілля, пелети' },
					{ title: 'Текстильні матеріали' },
					{ title: 'Гума, пластик, полімери' },
					{ title: 'Інша сировина' },
				],
			},
			{
				title: 'Ремонт та обслуговування техніки',
				link: '/electronics-repair-maintenance',
				subcategories: [
					{ title: 'Телефони і смартфони' },
					{ title: "Комп'ютерна техніка" },
					{ title: 'Побутова техніка' },
					{ title: 'Фото і відеоапаратура' },
					{ title: 'Тв і відеотехніка' },
					{ title: 'Аудіотехніка' },
					{ title: 'Кліматична техніка' },
					{ title: 'Ігрові приставки' },
					{ title: 'Оргтехніка, заправка картриджів' },
					{ title: 'Електротранспорт' },
					{ title: 'Електро та бензоінструмент' },
					{ title: 'Інша техніка' },
				],
			},
			{
				title: 'Побутові послуги',
				link: '/household',
				subcategories: [
					{ title: 'Хімчистка та прання' },
					{ title: 'Пошиття та ремонт одягу' },
					{ title: 'Ремонт взуття та сумок' },
					{ title: 'Дезінфекція та дезінсекція' },
					{ title: 'Аварійне відкриття замків' },
					{ title: 'Виготовлення ключів' },
					{ title: 'Послуги домробітниці' },
					{ title: 'Послуги асенізатора' },
					{ title: 'Вивезення сміття' },
					{ title: 'Послуги садівника, догляд за територією' },
					{ title: 'Інші побутові послуги' },
				],
			},
			{
				title: 'Клінінг',
				link: '/cleaning',
			},
			{
				title: 'Організація свят',
				link: '/event-organization',
				subcategories: [
					{ title: 'Аніматори та ростові ляльки' },
					{ title: 'Кейтеринг, кухарі' },
					{ title: 'Ведучі, музиканти, тамада' },
					{ title: 'Оформлення кульками' },
					{ title: 'Десерти та випічка на замовлення' },
					{ title: 'Інші послуги для свят' },
				],
			},
			{
				title: 'Ритуальні послуги',
				link: '/funeral',
				subcategories: [
					{ title: "Виготовлення пам'ятників" },
					{ title: 'Інші ритуальні послуги' },
				],
			},
			{
				title: 'Прийом вторсировини',
				link: '/recycling',
			},
			{
				title: 'Ділові послуги',
				link: '/business',
				subcategories: [
					{ title: 'Бухгалтерські послуги' },
					{ title: 'Створення сайтів' },
					{ title: 'Юридичні послуги' },
					{ title: 'Поліграфія, реклама, друк' },
					{ title: 'Фінансові послуги, партнерство' },
					{ title: 'Маркетингові послуги' },
					{ title: 'Послуги перекладачів, набір тексту' },
					{ title: 'Інші ділові послуги' },
				],
			},
		],
	},
	{
		title: 'Оренда та прокат',
		link: '/rent',
		color: '#c8f8f6',
		img: 'category/rent.png',
		subcategories: [
			{
				title: 'Оренда транспорту та спецтехніки',
				link: '/rental-transport_special-equipment',
				subcategories: [
					{ title: 'Авто' },
					{ title: 'Автобус, мікроавтобус' },
					{ title: 'Причеп' },
					{ title: 'Фура, трал, довгомір' },
					{ title: 'Самоскид, зерновоз' },
					{ title: 'Навантажувач' },
					{ title: 'Кран' },
					{ title: 'Автовишка' },
					{ title: 'Екскаватор, бульдозер' },
					{ title: 'Трактор, комбайн' },
					{ title: 'Інший транспорт' },
				],
			},
			{
				title: 'Прокат велосипедів і мото',
				link: '/bike-moto',
			},
			{
				title: 'Оренда обладнання',
				link: '/equipment',
				subcategories: [
					{ title: 'Оренда генераторів' },
					{ title: 'Оренда опалубки' },
					{ title: 'Оренда риштувань' },
					{ title: 'Оренда бетонозмішувачів та віброплит' },
					{ title: 'Оренда біотуалетів і побутівок' },
					{ title: 'Інше обладнання' },
				],
			},
			{
				title: 'Прокат інструментів',
				link: '/tool',
			},
			{
				title: 'Прокат товарів мед призначення',
				link: '/medical-equipment',
			},
			{
				title: 'Прокат техніки та електроніки',
				link: '/technology_electronics',
			},
			{
				title: 'Прокат товарів для заходів',
				link: '/event',
			},
			{
				title: 'Прокат спорт і туристичних товарів',
				link: '/sports-tourist',
			},
			{
				title: 'Прокат одягу та аксесуарів',
				link: '/clothing_accessories',
			},
			{
				title: 'Прокат дитячого одягу та товарів',
				link: '/childrens_clothing',
			},
			{
				title: 'Інші товари на прокат',
				link: '/other',
			},
		],
	},
	{
		title: 'Мода і стиль',
		link: '/fashion',
		img: 'category/fashion.png',
		color: '#ffd6c9',
		subcategories: [
			{
				title: "Краса / здоров'я",
				link: '/beauty_health',
				subcategories: [
					{
						title: 'Парфумерія',
						subcategories: [
							{ title: 'Духи (парфуми)' },
							{ title: 'Парфумована вода' },
							{ title: 'Парфумовані олії і масляні духи' },
							{ title: 'Туалетна вода' },
							{ title: 'Одеколон' },
							{ title: 'Набори' },
							{ title: 'Інше' },
						],
					},
					{
						title: 'Обладнання перукарень / салонів краси',
						subcategories: [
							{ title: 'Для манікюру і педикюру' },
							{ title: 'Для перукарні' },
							{ title: 'Для масажних салонів' },
							{ title: 'Для солярію' },
							{ title: 'Меблі для салонів краси' },
							{ title: 'Кільцеві лампи' },
							{ title: 'Інше' },
						],
					},
					{
						title: 'Товари для інвалідів',
						subcategories: [
							{ title: 'Коляски' },
							{ title: 'Тростини' },
							{ title: 'Милиці' },
							{ title: 'Ходунки' },
							{ title: 'Туалетні стільці' },
							{ title: 'Матраци від пролежнів' },
							{ title: 'Інше' },
						],
					},
					{
						title: 'Догляд за обличчям',
						subcategories: [
							{ title: 'Креми для обличчя' },
							{ title: 'Маски для обличчя' },
							{ title: 'Олія для обличчя' },
							{ title: 'Скраб для обличчя' },
							{ title: 'Спрей для обличчя' },
							{ title: 'Пілінг для обличчя' },
							{ title: 'Засоби для очищення обличчя' },
							{ title: 'Сонцезахисні засоби' },
							{ title: 'Тоніки для обличчя' },
							{ title: 'Міцелярна вода' },
							{ title: 'Сироватки для обличчя' },
							{ title: 'Догляд за очима' },
							{ title: 'Інше' },
						],
					},
					{
						title: 'Макіяж / декоративна косметика',
						subcategories: [
							{ title: 'Туш' },
							{ title: 'Тіні' },
							{ title: 'Контурні олівці' },
							{ title: 'Підводка' },
							{ title: 'Коректори' },
							{ title: 'Накладні вії' },
							{ title: 'Губна помада' },
							{ title: 'Блиск для губ' },
							{ title: 'Тінт для губ' },
							{ title: 'Бальзами для губ' },
							{ title: 'Косметика для брів' },
							{ title: 'Тональний крем' },
							{ title: 'Пудри' },
							{ title: 'Хайлайтер' },
							{ title: "Рум'яна" },
							{ title: 'Бронзери' },
							{ title: 'BB-креми і CC-креми' },
							{ title: 'Набори' },
							{ title: 'Бази / праймери під макіяж' },
							{ title: 'Пензлі' },
							{ title: 'Інше' },
						],
					},
					{
						title: 'Косметика для волосся',
						subcategories: [
							{ title: 'Шампуні' },
							{ title: 'Кондиціонери для волосся' },
							{ title: 'Бальзами для волосся' },
							{ title: 'Лосьйони для волосся' },
							{ title: 'Олія для волосся' },
							{ title: 'Лаки для волосся' },
							{ title: 'Мус для волосся' },
							{ title: 'Засоби від лупи' },
							{ title: 'Засоби від випадіння волосся' },
							{ title: 'Термозахист' },
							{ title: 'Канекалони' },
							{ title: 'Маски для волосся' },
							{ title: 'Інше' },
						],
					},
					{
						title: 'Фарбування',
						subcategories: [
							{ title: 'Фарба для волосся' },
							{ title: 'Тонуючі засоби' },
							{ title: 'Окислювач для волосся' },
							{ title: 'Знебарвлення та освітлення' },
							{ title: 'Хна' },
							{ title: 'Інше' },
						],
					},
					{
						title: 'Косметика для тіла',
						subcategories: [
							{ title: 'Дезодоранти і антиперспіранти' },
							{ title: 'Гелі для душу' },
							{ title: 'Мило' },
							{ title: 'Креми для тіла' },
							{ title: 'Скраби для тіла' },
							{ title: 'Сіль для ванни' },
							{ title: 'Піна для ванни' },
							{ title: 'Засоби для засмаги' },
							{ title: 'Косметика для рук' },
							{ title: 'Крем для рук' },
							{ title: 'Косметика для ніг' },
							{ title: 'Крем для ніг' },
							{ title: 'Дезодорант для ніг' },
							{ title: 'Масла для тіла' },
							{ title: 'Інше' },
						],
					},
					{
						title: 'Для ротової порожнини',
						subcategories: [
							{ title: 'Зубні пасти' },
							{ title: 'Зубні щітки' },
							{ title: 'Зубний порошок' },
							{ title: 'Ополіскувачі для порожнини рота, зубів, ясен' },
							{ title: 'Дорожні набори' },
							{ title: 'Інше' },
						],
					},
					{
						title: 'Для нігтів',
						subcategories: [
							{ title: 'Гель-лаки' },
							{ title: 'Лаки для нігтів' },
							{ title: 'Рідина для зняття лаку' },
							{ title: 'Декор для нігтів' },
							{ title: 'Догляд за кутикулою' },
							{ title: 'Накладні нігті' },
							{ title: 'Інструменти для манікюру та педикюру' },
							{ title: 'Стартовий набір для манікюру' },
							{ title: 'Інше' },
						],
					},
					{
						title: 'Для гоління',
						subcategories: [
							{ title: 'Косметика для гоління' },
							{ title: 'Станок для гоління' },
							{ title: 'Леза для гоління' },
							{ title: 'Косметика після гоління' },
							{ title: 'Крем для депіляції' },
							{ title: 'Віск для депіляції' },
							{ title: 'Паста для шугарінгу' },
							{ title: 'Інше' },
						],
					},
					{
						title: 'Гігієнічні засоби',
						subcategories: [
							{ title: 'Прокладки' },
							{ title: 'Тампони' },
							{ title: 'Антисептики' },
							{ title: 'Підгузки для дорослих' },
							{ title: 'Менструальні чаші' },
							{ title: 'Засоби для інтимної гігієни' },
							{ title: 'Інше' },
						],
					},
					{
						title: 'Ортопедичні товари',
						subcategories: [
							{ title: 'Пристосування для стоп' },
							{ title: 'Фіксатори' },
							{ title: 'Корсети, коректори постави' },
							{ title: 'Наколінники' },
							{ title: 'Бандажі та пояси' },
							{ title: 'Гіпс, бинти, тейпи' },
							{ title: 'Ортези' },
							{ title: 'Інші ортопедичні товари' },
						],
					},
					{
						title: 'Медичне приладдя',
						subcategories: [
							{ title: 'Одноразові шапочки' },
							{ title: 'Медичні рукавиці' },
							{ title: "Перев'язувальні матеріали" },
							{ title: 'Медичні маски і респіратори' },
							{ title: 'Інше' },
						],
					},
					{
						title: 'Косметичні інструменти та аксесуари',
						subcategories: [
							{ title: 'Дзеркала для макіяжу' },
							{ title: 'Пінцети та щипці' },
							{ title: 'Гребінці' },
							{ title: 'Спонжі' },
							{ title: 'Інструменти для чистки обличчя' },
							{ title: 'Органайзери для косметики' },
							{ title: 'Бігуді' },
							{ title: 'Мочалки для душу' },
							{ title: 'Щітки для сухого масажу' },
							{ title: 'Інше' },
						],
					},
					{ title: "Інші товари для краси і здоров'я" },
				],
			},
			{
				title: 'Для весілля',
				link: '/wedding',
				subcategories: [
					{ title: 'Весільні сукні' },
					{ title: 'Весільні костюми' },
					{ title: 'Сукні для подружок нареченої' },
					{
						title: 'Весільне взуття',
						subcategories: [
							{ title: 'Туфлі' },
							{ title: 'Босоніжки' },
							{ title: 'Балетки' },
							{ title: 'Ботильйони' },
							{ title: 'Черевики і кросівки' },
						],
					},
					{
						title: 'Весільні аксесуари для нареченої',
						subcategories: [
							{ title: "Підв'язки для нареченої" },
							{ title: 'Шубки' },
							{ title: 'Накидки' },
							{ title: 'Болеро' },
							{ title: "Під'юбники" },
							{ title: 'Віяла і сумочки' },
							{ title: 'Парасолі' },
							{ title: 'Фата' },
							{ title: 'Весільні рукавички і пояси' },
							{ title: 'Весільні ювелірні вироби та прикраси' },
						],
					},
					{ title: 'Весільна білизна' },
					{
						title: 'Весільні аксесуари (декор)',
						subcategories: [
							{ title: 'Бутоньєрки' },
							{ title: 'Подушки для обручок' },
							{ title: 'Прикраси на машину' },
							{ title: 'Весільна арка' },
							{ title: 'Весільні келихи' },
							{ title: 'Скриньки для грошей' },
							{ title: 'Весільні букети' },
							{ title: 'Запрошення на весілля' },
							{ title: 'Весільний рушник' },
						],
					},
					{ title: 'Інше' },
				],
			},
			{
				title: 'Аксесуари',
				link: '/accessories',
				subcategories: [
					{
						title: 'Ювелірні вироби',
						subcategories: [
							{ title: 'Каблучки' },
							{ title: 'Сережки' },
							{ title: 'Браслети' },
							{ title: 'Підвіски' },
							{ title: 'Брошки' },
							{ title: 'Ланцюжки' },
							{ title: 'Прикраси для пірсингу' },
							{ title: 'Кольє' },
							{ title: 'Шпильки' },
							{ title: 'Запонки' },
							{ title: 'Шарми' },
							{ title: 'Набори' },
							{ title: 'Інше' },
						],
					},
					{
						title: 'Сумки',
						subcategories: [
							{ title: 'Шкіряні сумки' },
							{ title: 'Клатчі' },
							{ title: 'Пляжні сумки' },
							{ title: 'Поясні сумки' },
							{ title: 'Спортивні сумки' },
							{ title: 'Сумки через плече' },
							{ title: 'Портфелі' },
							{ title: 'Шоппери' },
							{ title: 'Барсетки' },
							{ title: 'Валізи' },
							{ title: 'Аксесуари для сумок' },
							{ title: 'Дорожні сумки' },
							{ title: 'Інше' },
						],
					},
					{
						title: 'Біжутерія',
						subcategories: [
							{ title: 'Каблучки' },
							{ title: 'Сережки' },
							{ title: 'Браслети' },
							{ title: 'Кулони / підвіски' },
							{ title: 'Брошки' },
							{ title: 'Ланцюжки' },
							{ title: 'Чокери' },
							{ title: 'Запонки' },
							{ title: 'Кліпси' },
							{ title: 'Шпильки' },
							{ title: 'Бісер / фурнітура' },
							{ title: 'Кольє' },
							{ title: 'Набори біжутерії' },
							{ title: 'Інше' },
						],
					},
					{ title: 'Скриньки для прикрас' },
					{
						title: 'Рюкзаки міські та спортивні',
						subcategories: [
							{ title: 'Рюкзаки для ноутбука' },
							{ title: 'Рюкзаки для подорожей' },
							{ title: 'Міські рюкзаки' },
							{ title: 'Інше' },
						],
					},
					{
						title: 'Гаманці, косметички, візитниці',
						subcategories: [
							{ title: 'Візитниці та картхолдери' },
							{ title: 'Гаманці' },
							{ title: 'Косметички' },
							{ title: 'Чохли для ключів' },
							{ title: 'Затискачі для грошей' },
							{ title: 'Інше' },
						],
					},
					{ title: 'Парасолі' },
					{
						title: 'Аксесуари для волосся',
						subcategories: [
							{ title: "Пов'язки" },
							{ title: 'Гумки' },
							{ title: 'Заколки' },
							{ title: 'Обручі' },
							{ title: 'Шпильки' },
							{ title: 'Інше' },
						],
					},
					{
						title: 'Ремені та пояси',
						subcategories: [
							{ title: 'Ремені' },
							{ title: 'Підтяжки' },
							{ title: 'Пояси' },
							{ title: 'Шнурки' },
							{ title: 'Портупеї' },
							{ title: 'Інше' },
						],
					},
					{
						title: 'Шарфи і рукавички',
						subcategories: [
							{ title: 'Носові хустинки' },
							{ title: 'Палантини і шалі' },
							{ title: 'Хустки' },
							{ title: 'Снуди' },
							{ title: 'Шарфи' },
							{ title: 'Рукавички' },
							{ title: 'Рукавиці' },
							{ title: 'Інше' },
						],
					},
					{
						title: 'Окуляри',
						subcategories: [
							{ title: 'Оправи' },
							{ title: 'Сонцезахисні окуляри' },
							{ title: 'Окуляри для зору' },
							{ title: "Комп'ютерні окуляри" },
							{ title: 'Контактні лінзи' },
							{ title: 'Чохли для окулярів' },
							{ title: 'Аксесуари для окулярів і лінз' },
							{ title: 'Інше' },
						],
					},
					{
						title: 'Краватки і метелики',
						subcategories: [{ title: 'Краватки' }, { title: 'Метелики' }],
					},
					{
						title: 'Аксесуари для взуття',
						subcategories: [
							{ title: 'Устілки для взуття' },
							{ title: 'Креми, щітки та інші аксесуари' },
							{ title: 'Шнурки для взуття' },
						],
					},
					{ title: 'Ремінці та браслети для годинника' },
					{ title: 'Маски для сну' },
					{ title: 'Інші аксесуари' },
				],
			},
			{
				title: 'Наручні годинники',
				link: '/wristwatches',
			},
			{
				title: 'Подарунки',
				link: '/gifts',
				subcategories: [
					{ title: 'Подарунки для чоловіків' },
					{ title: 'Подарунки для жінок' },
					{ title: 'Подарунки для дітей' },
					{ title: 'Подарунки на день народження' },
					{ title: 'Подарунки на весілля' },
					{ title: 'Подарунки на 8 березня' },
					{ title: 'Подарунки на Новий рік' },
					{ title: 'Подарунки колегам' },
					{ title: 'Смачні подарунки' },
					{ title: 'Подарункові коробки та пакування' },
					{
						title: 'Подарунки ручної роботи',
						subcategories: [
							{ title: 'Мило ручної роботи' },
							{ title: 'Свічки ручної роботи' },
							{ title: 'Іграшки ручної роботи' },
							{ title: 'Інші подарунки ручної роботи' },
						],
					},
					{ title: 'Листівки та конверти' },
					{ title: 'Букети' },
					{ title: 'Повітряні кульки та композиції з них' },
					{ title: 'Інші подарунки' },
				],
			},
			{
				title: 'Мода різне',
				link: '/fashion-various',
			},
			{
				title: 'Чоловіча білизна та плавки',
				link: '/mens-underwear_swimwear',
				subcategories: [
					{ title: 'Труси' },
					{ title: 'Термобілизна' },
					{ title: 'Шкарпетки' },
					{ title: 'Плавки' },
					{ title: 'Інша чоловіча білизна' },
				],
			},
			{
				title: 'Жіноча білизна та купальники',
				link: '/womens-underwear_swimwear',
				subcategories: [
					{ title: 'Пляжні сукні та туніки' },
					{ title: 'Парео, накидки' },
					{ title: 'Пляжні шорти' },
					{
						title: 'Купальники',
						subcategories: [
							{ title: 'Роздільні купальники' },
							{ title: 'Суцільні купальники' },
							{ title: 'Спортивні купальники' },
							{ title: 'Інші купальники' },
						],
					},
					{ title: 'Труси' },
					{
						title: 'Бюстгалтери',
						subcategories: [
							{ title: 'Балконет' },
							{ title: 'Бандо (без бретелів)' },
							{ title: 'Бралетт (без кісточок)' },
							{ title: 'Бюстгалтери з Push up' },
							{ title: 'Безшовні бюстгалтери' },
							{ title: "М'які бюстгалтери" },
							{ title: 'Бюстгалтери топи' },
							{ title: 'Інші бюстгалтери' },
						],
					},
					{ title: 'Комплекти спідньої білизни' },
					{
						title: 'Корегуюча білизна',
						subcategories: [
							{ title: 'Корегуючі шорти і панталони' },
							{ title: 'Корегуючі пояси' },
							{ title: 'Корегуючі труси' },
							{ title: 'Корегуючі корсети' },
							{ title: 'Корегуючі боді' },
							{ title: 'Інша корегуюча білизна' },
						],
					},
					{ title: 'Термобілизна' },
					{ title: 'Еротична білизна' },
					{ title: 'Корсети' },
					{ title: 'Комбінації' },
					{ title: 'Топи бюстьє' },
					{ title: "Пояси і підв'язки для панчох" },
					{ title: 'Комбідреси' },
					{
						title: 'Панчохи / шкарпетки / колготки',
						subcategories: [
							{ title: 'Шкарпетки' },
							{ title: 'Панчохи' },
							{ title: 'Колготки' },
							{ title: 'Гетри та гольфи' },
							{ title: 'Сліди' },
							{ title: 'Компресійні панчохи' },
							{ title: 'Інше' },
						],
					},
					{ title: 'Інша жіноча білизна' },
				],
			},
			{
				title: 'Одяг для вагітних',
				link: '/maternity-clothing',
				subcategories: [
					{ title: 'Футболки та майки для вагітних та годуючих' },
					{ title: 'Блузки та туніки для вагітних та годуючих' },
					{ title: 'Плаття для вагітних та годуючих' },
					{ title: 'Спідниці для вагітних' },
					{ title: 'Купальники для вагітних' },
					{ title: 'Нижня білизна для вагітних та годуючих' },
					{ title: 'Шорти для вагітних' },
					{ title: 'Комбінезони для вагітних та годуючих' },
					{ title: 'Штани і легінси для вагітних' },
					{ title: 'Джинси для вагітних' },
					{ title: 'Колготки для вагітних' },
					{ title: 'Верхній одяг для вагітних' },
					{ title: 'Одяг для сну і дому для вагітних та годуючих' },
					{ title: 'Светри і толстовки для вагітних та годуючих' },
					{ title: 'Костюми для вагітних та годуючих' },
					{ title: 'Сарафани для вагітних та годуючих' },
					{ title: 'Пояси для вагітних та годуючих' },
					{ title: 'Інший одяг для вагітних' },
				],
			},
			{
				title: 'Головні убори',
				link: '/headwear',
				subcategories: [
					{ title: 'Бейсболки та кепки' },
					{ title: 'Балаклави' },
					{ title: 'Комплекти' },
					{ title: 'Панами' },
					{ title: 'Капелюхи' },
					{ title: 'Шапки' },
					{ title: 'Берети' },
					{ title: 'Бандани, бафи' },
					{ title: "Пов'язки та хутряні навушники" },
					{ title: 'Інші головні убори' },
				],
			},
			{
				title: 'Чоловіче взуття',
				link: '/mens-footwear',
				subcategories: [
					{
						title: 'Кросівки',
						subcategories: [
							{ title: 'Кросівки для бігу' },
							{ title: 'Кросівки для міста' },
							{ title: 'Кросівки для залу і тренувань' },
							{ title: 'Трекінгові кросівки' },
							{ title: 'Інші кросівки' },
						],
					},
					{ title: 'Кеди' },
					{
						title: 'Черевики',
						subcategories: [
							{ title: 'Челсі' },
							{ title: 'Берці' },
							{ title: 'Напівчеревики' },
							{ title: 'Трекінгові черевики' },
							{ title: 'Інші черевики' },
						],
					},
					{
						title: 'Сандалі і шльопанці',
						subcategories: [
							{ title: 'Сандалі' },
							{ title: 'Шльопанці' },
							{ title: "В'єтнамки" },
							{ title: 'Аквашузи (коралоходи)' },
							{ title: 'Інше' },
						],
					},
					{
						title: 'Чоботи',
						subcategories: [
							{ title: 'Мунбути' },
							{ title: 'Уггі та унти чоловічі' },
							{ title: 'Дутики' },
							{ title: 'Гумові чоботи' },
							{ title: 'Інші чоботи' },
						],
					},
					{ title: 'Домашні капці' },
					{
						title: 'Мокасини та сліпони',
						subcategories: [
							{ title: 'Топсайдери' },
							{ title: 'Мокасини' },
							{ title: 'Сліпони' },
							{ title: 'Еспадрилі' },
							{ title: 'Інше' },
						],
					},
					{ title: 'Ортопедичне взуття' },
					{
						title: 'Туфлі',
						subcategories: [
							{ title: 'Монки' },
							{ title: 'Оксфорди' },
							{ title: 'Дербі' },
							{ title: 'Лофери' },
							{ title: 'Броги' },
							{ title: 'Інші туфлі' },
						],
					},
					{ title: 'Інше чоловіче взуття' },
				],
			},
			{
				title: 'Жіноче взуття',
				link: '/womens-footwear',
				subcategories: [
					{
						title: 'Черевики та напівчеревики',
						subcategories: [
							{ title: 'Ботильйони' },
							{ title: 'Челсі' },
							{ title: 'Хайтопи' },
							{ title: 'Берці' },
							{ title: 'Броги' },
							{ title: 'Хайкери' },
							{ title: 'Дезерти' },
							{ title: 'Козаки' },
							{ title: 'Інші черевики та напівчеревики' },
						],
					},
					{
						title: 'Туфлі',
						subcategories: [
							{ title: 'Балетки' },
							{ title: 'Дербі' },
							{ title: 'Лофери' },
							{ title: 'Туфлі-човники' },
							{ title: 'Оксфорди' },
							{ title: 'Інші туфлі' },
						],
					},
					{
						title: 'Чоботи, напівчоботи',
						subcategories: [
							{ title: 'Дутики' },
							{ title: 'Ботфорти' },
							{ title: 'Місяцеходи' },
							{ title: 'Гумові чоботи' },
							{ title: 'Унти' },
							{ title: 'Інше' },
						],
					},
					{ title: 'Уггі' },
					{
						title: 'Мокасини та сліпони',
						subcategories: [
							{ title: 'Мокасини' },
							{ title: 'Топсайдери' },
							{ title: 'Сліпони' },
							{ title: 'Еспадрилі' },
							{ title: 'Інше' },
						],
					},
					{
						title: 'Кросівки',
						subcategories: [
							{ title: 'Снікерси' },
							{ title: 'Кросівки-шкарпетки' },
							{ title: 'Кросівки для бігу' },
							{ title: 'Кросівки для фітнесу та тренувань' },
							{ title: 'Трекінгові кросівки' },
							{ title: 'Кросівки-хайтопи' },
							{ title: 'Інші кросівки' },
						],
					},
					{ title: 'Кеди' },
					{ title: 'Домашні капці' },
					{ title: 'Ортопедичне взуття' },
					{ title: 'Спортивне взуття' },
					{
						title: "Босоніжки, сандалі, в'єтнамки",
						subcategories: [
							{ title: 'Аквашузи (коралоходи)' },
							{ title: 'Босоніжки' },
							{ title: 'Сандалі' },
							{ title: 'Шльопанці' },
							{ title: 'Сланці' },
							{ title: "В'єтнамки" },
							{ title: 'Сабо' },
							{ title: 'Мюлі' },
							{ title: 'Інше' },
						],
					},
					{ title: 'Інше жіноче взуття' },
				],
			},
			{
				title: 'Жіночий одяг',
				link: '/womens-clothing',
				subcategories: [
					{
						title: 'Боді',
					},
					{
						title: 'Майки та футболки',
						subcategories: [
							{ title: 'Футболки' },
							{ title: 'Майки' },
							{ title: 'Топи' },
							{ title: 'Поло' },
							{ title: 'Лонгслів' },
							{ title: 'Інше' },
						],
					},
					{
						title: 'Блузи і сорочки',
						subcategories: [
							{ title: 'Блузи' },
							{ title: 'Сорочки' },
							{ title: 'Інше' },
						],
					},
					{
						title: 'Светри, кардигани, худі',
						subcategories: [
							{ title: 'Светри' },
							{ title: 'Кардигани' },
							{ title: 'Худі' },
							{ title: 'Світшоти' },
							{ title: 'Толстовки' },
							{ title: 'Гольфи / водолазки' },
							{ title: 'Кофтинки' },
							{ title: 'Джемпери' },
							{ title: 'Накидки' },
							{ title: 'Пончо' },
							{ title: 'Інше' },
						],
					},
					{
						title: 'Плаття',
						subcategories: [
							{ title: 'Вечірні сукні' },
							{ title: 'Туніки' },
							{ title: 'Сарафани' },
							{ title: 'Повсякденні сукні' },
							{ title: 'Коктейльні сукні' },
							{ title: 'Ділові сукні' },
							{ title: 'Випускні сукні' },
							{ title: 'Сукня-піджак' },
							{ title: 'Сукні у білизняному стилі' },
							{ title: 'Інші плаття' },
						],
					},
					{
						title: 'Спідниці',
						subcategories: [
							{ title: 'Джинсові спідниці' },
							{ title: 'Спідниці олівець' },
							{ title: 'Шкіряні спідниці' },
							{ title: 'Спідниці довгі' },
							{ title: 'Плісировані спідниці' },
							{ title: 'Теплі спідниці' },
							{ title: 'Міні-спідниці' },
							{ title: 'Замшеві спідниці' },
							{ title: 'Спідниці міді' },
							{ title: 'Фатінові спідниці' },
							{ title: 'Спідниці-шорти' },
							{ title: 'Спідниці на запах' },
							{ title: 'Спідниці з екошкіри' },
							{ title: 'Інші спідниці' },
						],
					},
					{
						title: 'Верхній одяг',
						subcategories: [
							{ title: 'Плащі й тренчі' },
							{ title: 'Дощовики' },
							{ title: 'Пальто' },
							{ title: 'Вітровки' },
							{ title: 'Шкіряні куртки' },
							{ title: 'Бомбери' },
							{ title: 'Джинсові куртки' },
							{ title: 'Парки' },
							{ title: 'Пуховики і зимові куртки' },
							{ title: 'Шуби, кожухи' },
							{ title: 'Дублянки' },
							{ title: 'Жилетки' },
							{ title: 'Болеро' },
							{ title: 'Екошуби' },
							{ title: 'Анораки' },
							{ title: 'Косухи' },
							{ title: 'Куртки-сорочки' },
							{ title: 'Інший верхній одяг' },
						],
					},
					{
						title: 'Джинси',
						subcategories: [
							{ title: 'Джинси-мом' },
							{ title: 'Джеггінси' },
							{ title: 'Джинси-бойфренди' },
							{ title: 'Прямі джинси' },
							{ title: 'Вузькі джинси / Skinny' },
							{ title: 'Високі джинси / Джинси з високою талією' },
							{ title: 'Джинси утеплені' },
							{ title: 'Рвані джинси' },
							{ title: 'Джинси кльош' },
							{ title: 'Джинси кюлоти' },
							{ title: 'Широкі джинси' },
							{ title: 'Інші джинси' },
						],
					},
					{
						title: 'Шорти',
						subcategories: [
							{ title: 'Джинсові шорти' },
							{ title: 'Шкіряні шорти' },
							{ title: 'Трикотажні шорти' },
							{ title: 'Шорти з високою талією' },
							{ title: 'Бриджі та капрі' },
							{ title: 'Шорти-бермуди' },
							{ title: 'Велосипедки' },
							{ title: 'Інші шорти' },
						],
					},
					{
						title: 'Брюки',
						subcategories: [
							{ title: 'Класичні брюки' },
							{ title: 'Штани чінос' },
							{ title: 'Штани карго' },
							{ title: 'Лляні штани' },
							{ title: 'Вельветові штани' },
							{ title: 'Лосини і легінси' },
							{ title: 'Брюки з високою талією' },
							{ title: 'Укорочені брюки' },
							{ title: 'Шкіряні брюки' },
							{ title: 'Широкі брюки' },
							{ title: 'Брюки кльош' },
							{ title: 'Брюки-кюлоти' },
							{ title: 'Інші брюки' },
						],
					},
					{
						title: 'Комбінезони',
						subcategories: [
							{ title: 'Літні комбінезони' },
							{ title: 'Зимові комбінезони' },
							{ title: 'Комбінезони з брюками' },
							{ title: 'Комбінезони з шортами' },
							{ title: 'Джинсові комбінезони' },
							{ title: 'Вечірні комбінезони' },
							{ title: 'Інші комбінезони' },
						],
					},
					{
						title: 'Костюми',
						subcategories: [
							{ title: 'Костюми зі спідницею' },
							{ title: 'Костюми з брюками' },
							{ title: 'Костюми з шортами' },
							{ title: 'Інше' },
						],
					},
					{
						title: 'Жіночі піджаки та жакети',
						subcategories: [
							{ title: 'Піджаки оверсайз' },
							{ title: 'Джинсові піджаки' },
							{ title: 'Шкіряні піджаки' },
							{ title: 'Інші піджаки та жакети' },
						],
					},
					{
						title: 'Домашній одяг та одяг для сну',
						subcategories: [
							{ title: 'Піжами' },
							{ title: 'Халати' },
							{ title: 'Кігурумі' },
							{ title: 'Нічні сорочки' },
							{ title: 'Пеньюари' },
							{ title: 'Домашні костюми' },
							{ title: 'Домашні сукні' },
							{ title: 'Домашні штани та брюки' },
							{ title: 'Інше' },
						],
					},
					{
						title: 'Спортивний одяг',
						subcategories: [
							{ title: 'Лижні костюми' },
							{ title: 'Спортивна білизна' },
							{ title: 'Спортивні лосини' },
							{ title: 'Джоггери' },
							{ title: 'Спортивні капрі та бриджі' },
							{ title: 'Лижні куртки' },
							{ title: 'Лижні комбінезони' },
							{ title: 'Лижні штани та брюки' },
							{ title: 'Штани для сноубордів' },
							{ title: 'Куртки для сноубордів' },
							{ title: 'Спортивні костюми' },
							{ title: 'Спортивні футболки' },
							{ title: 'Спортивні майки' },
							{ title: 'Спортивні топи' },
							{ title: 'Спортивні спідниці' },
							{ title: 'Спортивні сукні' },
							{ title: 'Спортивні шорти' },
							{ title: 'Спортивні комбінезони' },
							{ title: 'Спортивні кофти' },
							{ title: 'Спортивні куртки і ветровки' },
							{ title: 'Спортивні штани та брюки' },
							{ title: 'Інший спортивний одяг' },
						],
					},
					{
						title: 'Вишиванки',
						subcategories: [
							{ title: 'Національні костюми' },
							{ title: 'Сорочки та блузки вишиванки' },
							{ title: 'Сукні вишиванки' },
							{ title: 'Футболки вишиванки' },
							{ title: 'Інші вишиванки' },
						],
					},
					{
						title: 'Інший жіночий одяг',
					},
				],
			},
			{
				title: 'Чоловічий одяг',
				link: '/mens-clothing',
				subcategories: [
					{
						title: 'Футболки та майки',
						subcategories: [
							{ title: 'Футболки' },
							{ title: 'Лонгслів' },
							{ title: 'Майки' },
							{ title: 'Поло' },
							{ title: 'Інше' },
						],
					},
					{
						title: 'Сорочки і теніски',
						subcategories: [
							{ title: 'Сорочки' },
							{ title: 'Вишиванки' },
							{ title: 'Теніски' },
							{ title: 'Інше' },
						],
					},
					{
						title: 'Кофти й светри',
						subcategories: [
							{ title: 'Худі' },
							{ title: 'Світшот' },
							{ title: 'Толстовки' },
							{ title: 'Мантія' },
							{ title: 'Олімпійка' },
							{ title: 'Гольф / водолазка' },
							{ title: 'Светр' },
							{ title: 'Кардиган' },
							{ title: 'Светр реглан' },
							{ title: 'Кофти' },
							{ title: 'Інше' },
						],
					},
					{
						title: 'Верхній одяг',
						subcategories: [
							{ title: 'Дощовики' },
							{ title: 'Плащі' },
							{ title: 'Пальто' },
							{ title: 'Вітровки' },
							{ title: 'Шкіряні куртки' },
							{ title: 'Бомбери' },
							{ title: 'Джинсові куртки' },
							{ title: 'Парки' },
							{ title: 'Пуховики та зимові куртки' },
							{ title: 'Шуби та дублянки' },
							{ title: 'Жилети' },
							{ title: 'Анорак' },
							{ title: 'Косуха' },
							{ title: 'Інший верхній одяг' },
						],
					},
					{
						title: 'Шорти',
						subcategories: [
							{ title: 'Джинсові шорти' },
							{ title: 'Бриджі' },
							{ title: 'Карго' },
							{ title: 'Класичні шорти' },
							{ title: 'Шорти бермуди' },
							{ title: 'Пляжні шорти' },
							{ title: 'Інші шорти' },
						],
					},
					{
						title: 'Джинси',
						subcategories: [
							{ title: 'Завужені джинси (Skinny)' },
							{ title: 'Прямі джинси' },
							{ title: 'Широкі джинси' },
							{ title: 'Джинсові джогери' },
							{ title: 'Класичні джинси' },
							{ title: 'Інші джинси' },
						],
					},
					{
						title: 'Штани',
						subcategories: [
							{ title: 'Джогери' },
							{ title: 'Завужені штани' },
							{ title: 'Чіноси' },
							{ title: 'Широкі штани' },
							{ title: 'Карго' },
							{ title: 'Класичні штани' },
							{ title: 'Інші штани' },
						],
					},
					{
						title: 'Костюми та піджаки',
						subcategories: [
							{ title: 'Чоловічі піджаки' },
							{ title: 'Смокінги' },
							{ title: 'Жилетки' },
							{ title: 'Блейзери' },
							{ title: 'Класичні костюми' },
							{ title: 'Інше' },
						],
					},
					{ title: 'Комбінезони' },
					{
						title: 'Одяг для дому та сну',
						subcategories: [
							{ title: 'Домашній одяг' },
							{ title: 'Піжами' },
							{ title: 'Халати' },
							{ title: 'Інше' },
						],
					},
					{
						title: 'Спортивний одяг',
						subcategories: [
							{ title: 'Спортивні костюми' },
							{ title: 'Спортивні футболки та майки' },
							{ title: 'Спортивні шкарпетки, гетри' },
							{ title: 'Спортивні куртки' },
							{ title: 'Спортивні шорти' },
							{ title: 'Тайтси і легінси' },
							{ title: 'Лижні куртки' },
							{ title: 'Спортивні кофти та светри' },
							{ title: 'Лижні костюми' },
							{ title: 'Лижні штани' },
							{ title: 'Лижні комбінезони' },
							{ title: 'Куртки для сноубордів' },
							{ title: 'Штани для сноубордів' },
							{ title: 'Одяг для тренажерного залу' },
							{ title: 'Одяг для бігу' },
							{ title: 'Спортивні штани' },
							{ title: 'Джогери' },
							{ title: 'Інший спортивний одяг' },
						],
					},
					{ title: 'Інший чоловічий одяг' },
				],
			},
			{
				title: 'Спецодяг, спецвзуття та аксесуари',
				link: '/workwear_footwear_accessories',
				subcategories: [
					{
						title: 'Робочий спецодяг',
						subcategories: [
							{ title: 'Робочі штани' },
							{ title: 'Робочі куртки' },
							{ title: 'Робочі комбінезони' },
							{ title: 'Робочі костюми' },
						],
					},
					{
						title: 'Медичний одяг',
						subcategories: [
							{ title: 'Медичні халати' },
							{ title: 'Медичні костюми' },
						],
					},
					{ title: 'Світловідбиваючі жилети' },
					{ title: 'Одноразовий одяг' },
					{ title: 'Дощовики' },
					{ title: 'Засоби захисту органів дихання' },
					{
						title: 'Робоче взуття',
						subcategories: [
							{ title: 'Робочі черевики' },
							{ title: 'Робочі чоботи' },
							{ title: 'Робочі кросівки' },
							{ title: 'Інше робоче взуття' },
						],
					},
					{ title: 'Інше' },
				],
			},
		],
	},
	{
		title: 'Хобі, відпочинок і спорт',
		link: '/hobby',
		img: 'category/hobby.png',
		color: '#fff6d9',
		subcategories: [
			{
				title: 'Музичні інструменти',
				link: '/musical-instruments',
				subcategories: [
					{ title: 'Акустичні гітари' },
					{ title: 'Бас-гітари' },
					{ title: 'Інше' },
					{ title: 'Піаніно / фортепіано / роялі' },
					{ title: 'Електрогітари' },
					{ title: 'Духові інструменти' },
					{ title: 'Комбопідсилювачі' },
					{ title: 'Синтезатори' },
					{ title: 'Ударні інструменти' },
					{ title: 'Студійне обладнання' },
					{ title: 'Аксесуари для музичних інструментів' },
				],
			},
			{
				title: 'Книги / журнали',
				link: '/books_magazines',
			},
			{
				title: 'Антикваріат / колекції',
				link: '/antiques_collectibles',
				subcategories: [
					{ title: 'Антикварні меблі' },
					{ title: 'Букіністика' },
					{ title: 'Живопис' },
					{ title: 'Предмети мистецтва' },
					{ title: 'Колекціонування' },
					{ title: 'Витвори майстрів / рукоділля' },
				],
			},
			{
				title: 'Квитки',
				link: '/tickets',
			},
			{
				title: 'Пошук попутників',
				link: '/travel-companions',
			},
			{
				title: 'Пошук гуртів / музикантів',
				link: '/bands-musicians-search',
			},
			{
				title: 'CD / DVD / Платівки',
				link: '/cd_dvd_vinyl',
			},
			{
				title: 'Спорт / відпочинок',
				link: '/sports_recreation',
				subcategories: [
					{ title: 'Лижі / сноуборди' },
					{ title: 'Ковзани' },
					{ title: 'Роликові ковзани' },
					{ title: 'Атлетика / фітнес' },
					{
						title: 'Туризм',
						subcategories: [
							{ title: 'Ліхтарики' },
							{ title: 'Газові пальники (портативні газові плити)' },
							{ title: 'Газові балони' },
							{ title: 'GPS навігатори' },
							{ title: 'Палатки' },
							{ title: 'Спальні мішки' },
							{ title: 'Рюкзаки' },
							{ title: 'Інші туристичні товари' },
						],
					},
					{ title: 'Полювання / риболовля' },
					{ title: 'Ігри з ракеткою' },
					{ title: 'Водні види спорту' },
					{ title: 'Футбол' },
					{ title: 'Хокей' },
					{ title: 'Єдиноборства / бокс' },
					{ title: 'Настільні ігри' },
					{ title: 'Інші види спорту' },
				],
			},
			{
				title: 'Інше',
				link: '/other',
			},
			{
				title: 'Мілітарія',
				link: '/military',
				subcategories: [
					{
						title: 'Військовий одяг',
						subcategories: [
							{ title: 'Камуфляжні костюми' },
							{ title: 'Штани' },
							{ title: 'Футболки' },
							{ title: 'Сорочки' },
							{ title: 'Кофти' },
							{ title: 'Куртки' },
							{ title: 'Ремені' },
							{ title: 'Рукавички' },
							{ title: 'Шкарпетки' },
							{ title: 'Балаклави та підшоломники' },
							{ title: 'Кепки та бейсболки' },
							{ title: 'Панами' },
							{ title: 'Шапки' },
							{ title: 'Інший одяг' },
						],
					},
					{
						title: 'Військове взуття',
						subcategories: [
							{ title: 'Берці' },
							{ title: 'Кросівки' },
							{ title: 'Черевики та напівчеревики' },
							{ title: 'Інше взуття' },
						],
					},
					{
						title: 'Рюкзаки та сумки',
						subcategories: [
							{ title: 'Рюкзаки' },
							{ title: 'Сумки' },
							{ title: 'Баули' },
							{ title: 'Інше' },
						],
					},
					{
						title: 'Розвантажувальні системи',
						subcategories: [
							{ title: 'Жилети розвантажувальні' },
							{ title: 'Тактичні пояси' },
							{ title: 'Ремінно-плечові системи (РПС)' },
							{ title: 'Інше' },
						],
					},
					{
						title: 'Підсумки',
						subcategories: [
							{ title: 'Медичні підсумки' },
							{ title: 'Підсумки для гранат' },
							{ title: 'Підсумки для магазинів штурмових гвинтівок' },
							{ title: 'Сумки скидання магазинів' },
							{ title: 'Спеціальні та інші підсумки' },
						],
					},
					{
						title: 'Спорядження',
						subcategories: [
							{ title: 'Засоби маскування' },
							{ title: 'Тепловізори' },
							{ title: 'Нашивки, шеврони, жетони' },
							{ title: 'Кобури' },
							{ title: 'Ремені для зброї' },
							{ title: 'Пояси-патронташі' },
							{ title: 'Тактичні навушники' },
							{ title: 'Наколінники та налокітники' },
							{ title: 'Тактичні окуляри' },
							{ title: 'Інше спорядження' },
						],
					},
					{
						title: 'Збройові аксесуари',
						subcategories: [
							{ title: 'Коліматори' },
							{ title: 'Оптичні приціли' },
							{ title: 'Цівки, накладки, кріплення' },
							{ title: "Полум'ягасники, ДТК, глушники" },
							{ title: 'Приклади, рукоятки, сошки' },
							{ title: 'Інше' },
						],
					},
					{
						title: 'Медицина',
						subcategories: [
							{ title: 'Аптечки та медичні набори' },
							{ title: 'Джгути, турнікети' },
							{ title: 'Iнше' },
						],
					},
					{
						title: 'Захист',
						subcategories: [
							{ title: 'Бронепластини' },
							{ title: 'Бронежилети' },
							{ title: 'Каски та шоломи' },
						],
					},
				],
			},
			{
				title: 'Вело',
				link: '/bicycles',
				subcategories: [
					{ title: 'Велосипеди' },
					{ title: 'Велозахист' },
					{ title: 'Велоаксесуари' },
					{ title: 'Велозапчастини' },
					{ title: 'Електровелосипеди' },
				],
			},
			{
				title: 'Квадрокоптери та аксесуари',
				link: '/quadcopters-accessories',
				subcategories: [
					{ title: 'Квадрокоптери' },
					{ title: 'Аксесуари для квадрокоптерів' },
				],
			},
		],
	},
	{
		title: 'Віддам безкоштовно',
		link: '/free',
		img: 'category/free.png',
		color: '#3a77ff',
	},
	{
		title: 'Обмін',
		link: '/exchange',
		img: 'category/exchange.png',
		color: '#23e5db',
	},
]
