import { ICategory } from '@/interfaces/category.interface'

export const categoriesData: ICategory[] = [
	{
		title: 'Допомога',
		img: 'category/help.png',
		color: '#f2f3f5',
		link: '/help',
		subcategories: [
			{
				title: 'Потрібна допомога',
				link: '/need-help',
				subcategories: [
					{
						title: 'Ліки та Гігієнічні засоби',
					},
					{
						title: 'Житло',
					},
					{
						title: 'Транспорт',
					},
					{
						title: 'Для дітей',
					},
					{
						title: 'Одяг та взуття',
					},
					{
						title: 'Для тварин',
					},
					{
						title: 'Медична допомога',
					},
					{
						title: 'Їжа / Продукти',
					},
					{
						title: 'Інше',
					},
				],
			},
			{
				title: 'Пропоную допомогу',
				link: 'offer-help',
				subcategories: [
					{
						title: 'Ліки та Гігієнічні засоби',
					},
					{
						title: 'Житло',
					},
					{
						title: 'Транспорт',
					},
					{
						title: 'Для дітей',
					},
					{
						title: 'Одяг та взуття',
					},
					{
						title: 'Для тварин',
					},
					{
						title: 'Медична допомога',
					},
					{
						title: 'Їжа / Продукти',
					},
					{
						title: 'Інше',
					},
				],
			},
		],
	},
	{
		title: 'Дитячий світ',
		img: 'category/children.png',
		color: '#3a77ff',
		link: '/children_world',
		subcategories: [
			{
				title: 'Дитячі коляски',
				link: '/strollers',
			},
			{
				title: 'Дитячі меблі',
				link: '/furniture',
			},
			{
				title: 'Інші дитячі товари',
				link: '/other',
			},
			{
				title: 'Дитячі автокрісла',
				link: '/car-seats',
			},
			{
				title: 'Дитячий одяг',
				link: '/clothing',
				subcategories: [
					{
						title: 'Одяг для хлопчиків',
					},
					{
						title: 'Одяг для дівчаток',
					},
					{
						title: 'Одяг для новонароджених',
					},
				],
			},
			{
				title: 'Дитяче взуття',
				link: '/shoes',
			},
			{
				title: 'Іграшки',
				link: '/toys',
				subcategories: [
					{
						title: 'Конструктори',
					},
					{
						title: 'Ляльки та пупси',
					},
					{
						title: 'Аксесуари для ляльок та пупсів',
					},
					{
						title: 'Розвиваючі іграшки',
						subcategories: [
							{
								title: 'Мозаїки',
							},
							{
								title: 'Іграшки сортери',
							},
							{
								title: 'Інтерактивні іграшки',
							},
							{
								title: 'Бізіборди та куби',
							},
							{
								title: 'Ігрові центри',
							},
							{
								title: 'Дзиги',
							},
							{
								title: 'Іграшки неваляшки',
							},
							{
								title: 'Іграшки каталки',
							},
							{
								title: 'Музичні інструменти',
							},
							{
								title: 'Розвиваючі килимки',
							},
							{
								title: 'Інші розвиваючі ігри',
							},
						],
					},
					{
						title: "М'які іграшки",
						subcategories: [
							{
								title: "М'які тварини",
							},
							{
								title: 'Іграшки-подушки',
							},
							{
								title: "Інші м'які іграшки",
							},
						],
					},
					{
						title: 'Настільні ігри та пазли',
						subcategories: [
							{
								title: 'Пазли',
							},
							{
								title: '3D-пазли',
							},
							{
								title: 'Дитячі головоломки',
							},
							{
								title: 'Дитячі настільні ігри',
							},
							{
								title: 'Інші настільні ігри',
							},
						],
					},
					{
						title: 'Брязкальця та підвіски',
					},
					{
						title: 'Іграшки для купання',
					},
					{
						title: 'Іграшкова зброя',
						subcategories: [
							{
								title: 'Пістолети',
							},
							{
								title: 'Автомати',
							},
							{
								title: 'Бластери',
							},
							{
								title: 'Мечі та щити',
							},
							{
								title: 'Луки та арбалети',
							},
							{
								title: 'Водяна зброя',
							},
							{
								title: 'Інша іграшкова зброя',
							},
						],
					},
					{
						title: 'Ігрові фігурки',
						subcategories: [
							{
								title: 'Фігурки персонажів',
							},
							{
								title: 'Фігурки тварин',
							},
							{
								title: 'Інші фігурки',
							},
						],
					},
					{
						title: 'Іграшковий транспорт',
						subcategories: [
							{
								title: 'Залізниці та потяги',
							},
							{
								title: 'Машинки',
							},
							{
								title: 'Мотоцикли',
							},
							{
								title: 'Танки',
							},
							{
								title: 'Гелікоптери',
							},
							{
								title: 'Трактори',
							},
							{
								title: 'Літаки',
							},
							{
								title: 'Інший іграшковий транспорт',
							},
						],
					},
					{
						title: 'Набори для творчості',
					},
					{
						title: 'Ігрові набори',
						subcategories: [
							{
								title: 'Косметика для дівчаток',
							},
							{
								title: 'Набори професій',
							},
							{
								title: 'Дитячі кухні',
							},
							{
								title: 'Інші ігрові набори',
							},
						],
					},
					{
						title: 'Іграшки для пісочниці',
					},
					{
						title: "Дитячі м'ячі",
					},
					{
						title: 'Дитячі маски',
					},
					{
						title: 'Інші іграшки для дітей',
					},
				],
			},
			{
				title: 'Годування',
				link: '/feeding',
			},
			{
				title: 'Товари для школярів',
				link: '/school-supplies',
			},
			{
				title: 'Дитячий транспорт',
				link: '/transport',
			},
		],
	},
	{
		title: 'Нерухомість',
		img: 'category/real-estate.png',
		color: '#23e5db',
		link: '/real-estate',
		subcategories: [
			{
				title: 'Подобова оренда житла',
				link: '/daily',
				subcategories: [
					{
						title: 'Будинки подобово, погодинно',
					},
					{
						title: 'Квартири подобово, погодинно',
					},
					{
						title: 'Кімнати подобово, погодинно',
					},
					{
						title: 'Готелі, бази відпочинку',
					},
					{
						title: 'Хостели, койко-місця',
					},
					{
						title: 'Пропозиції Туроператорів',
					},
				],
			},
			{
				title: 'Будинки',
				link: '/houses',
				subcategories: [
					{
						title: 'Продаж будинків',
					},
					{
						title: 'Довгострокова оренда будинків',
					},
				],
			},
			{
				title: 'Нерухомість за кордоном',
				link: '/abroad',
			},
			{
				title: 'Земля',
				link: '/land',
				subcategories: [
					{
						title: 'Оренда землі',
					},
					{
						title: 'Продаж землі',
					},
				],
			},
			{
				title: 'Комерційна нерухомість',
				link: '/commercial',
				subcategories: [
					{
						title: 'Продаж комерційної нерухомості',
					},
					{
						title: 'Оренда комерційної нерухомості',
					},
					{
						title: 'Коворкінги',
					},
				],
			},
			{
				title: 'Гаражі, парковки',
				link: '/garages',
				subcategories: [
					{
						title: 'Оренда гаражів, парковок',
					},
					{
						title: 'Продаж гаражів, парковок',
					},
				],
			},
			{
				title: 'Кімнати',
				link: '/rooms',
				subcategories: [
					{
						title: 'Продаж кімнат',
					},
					{
						title: 'Довгострокова оренда кімнат',
					},
				],
			},
			{
				title: 'Квартири',
				link: '/apartments',
				subcategories: [
					{
						title: 'Продаж квартир',
					},
					{
						title: 'Довгострокова оренда квартир',
					},
				],
			},
		],
	},
	{
		title: 'Авто',
		img: 'category/auto.png',
		color: '#ff5636',
		link: '/transport',
		subcategories: [
			{
				title: 'Легкові автомобілі',
				link: '/cars',
				subcategories: [
					{ title: 'Acura' },
					{ title: 'Alfa Romeo' },
					{ title: 'Aston Martin' },
					{ title: 'Audi' },
					{ title: 'Bentley' },
					{ title: 'BMW' },
					{ title: 'BMW-Alpina' },
					{ title: 'Brilliance' },
					{ title: 'Buick' },
					{ title: 'BYD' },
					{ title: 'Cadillac' },
					{ title: 'Chana' },
					{ title: 'Chery' },
					{ title: 'Chevrolet' },
					{ title: 'Chrysler' },
					{ title: 'Citroen' },
					{ title: 'Dacia' },
					{ title: 'Dadi' },
					{ title: 'Daewoo' },
					{ title: 'Daihatsu' },
					{ title: 'Dodge' },
					{ title: 'FAW' },
					{ title: 'Ferrari' },
					{ title: 'Fiat' },
					{ title: 'Ford' },
					{ title: 'Geely' },
					{ title: 'GMC' },
					{ title: 'Great Wall' },
					{ title: 'Groz' },
					{ title: 'Honda' },
					{ title: 'Hummer' },
					{ title: 'Hyundai' },
					{ title: 'Infiniti' },
					{ title: 'Isuzu' },
					{ title: 'Iveco' },
					{ title: 'JAC' },
					{ title: 'Jaguar' },
					{ title: 'Jeep' },
					{ title: 'Kia' },
					{ title: 'Lamborghini' },
					{ title: 'Lancia' },
					{ title: 'Land Rover' },
					{ title: 'Lexus' },
					{ title: 'Lifan' },
					{ title: 'Lincoln' },
					{ title: 'Lotus' },
					{ title: 'Maserati' },
					{ title: 'Maybach' },
					{ title: 'Mazda' },
					{ title: 'McLaren' },
					{ title: 'Mercedes-Benz' },
					{ title: 'Mercury' },
					{ title: 'MG' },
					{ title: 'MINI' },
					{ title: 'Mitsubishi' },
					{ title: 'Nissan' },
					{ title: 'Oldsmobile' },
					{ title: 'Opel' },
					{ title: 'Peugeot' },
					{ title: 'Pontiac' },
					{ title: 'Porsche' },
					{ title: 'Proton' },
					{ title: 'Ram' },
					{ title: 'Ravon' },
					{ title: 'Renault' },
					{ title: 'Rolls-Royce' },
					{ title: 'Roewe' },
					{ title: 'Rover' },
					{ title: 'Saab' },
					{ title: 'Samand' },
					{ title: 'Samsung' },
					{ title: 'Seat' },
					{ title: 'Shelby' },
					{ title: 'Skoda' },
					{ title: 'Smart' },
					{ title: 'SsangYong' },
					{ title: 'Subaru' },
					{ title: 'Suzuki' },
					{ title: 'TATA' },
					{ title: 'Tesla' },
					{ title: 'Toyota' },
					{ title: 'Volkswagen' },
					{ title: 'Volvo' },
					{ title: 'Wartburg' },
					{ title: 'ZX' },
					{ title: 'Богдан' },
					{ title: 'ВАЗ' },
					{ title: 'ГАЗ' },
					{ title: 'ЗАЗ' },
					{ title: 'ИЖ' },
					{ title: 'ЛуАЗ' },
					{ title: 'Москвич / АЗЛК' },
					{ title: 'РАФ' },
					{ title: 'УАЗ' },
					{ title: 'Інші' },
				],
			},
			{
				title: 'Мото',
				link: '/motorcycles',
				subcategories: [
					{ title: 'Мотоцикли' },
					{ title: 'Мопеди / скутери' },
					{ title: 'Квадроцикли' },
					{ title: 'Електросамокати / гіроскутери' },
					{ title: 'Електроскутери' },
					{ title: 'Максі-скутер' },
					{ title: 'Електромотоцикли' },
					{ title: 'Електроквадрацикли' },
					{ title: 'Баггі' },
					{ title: 'Картинг' },
					{ title: 'Снігохід' },
					{ title: 'Мото - інше' },
				],
			},
			{
				title: 'Інший транспорт',
				link: '/other',
				subcategories: [
					{ title: 'Літаки' },
					{ title: 'Гелікоптери' },
					{ title: 'Дельтаплани' },
					{ title: 'Карети' },
					{ title: 'Залізничні тепловози' },
					{ title: 'Залізничні вагони' },
					{ title: 'Інші види транспорту' },
				],
			},
			{
				title: 'Вантажні автомобілі',
				link: '/trucks',
			},
			{
				title: 'Автобуси',
				link: '/buses',
			},
			{
				title: 'Водний транспорт',
				link: '/water-transport',
				subcategories: [
					{ title: 'Яхта' },
					{ title: 'Катер' },
					{ title: 'Моторний човен' },
					{ title: 'Катамаран' },
					{ title: 'Гребний човен' },
					{ title: 'Гідроцикл' },
					{ title: 'Каяк' },
					{ title: 'Інший водний транспорт' },
				],
			},
			{
				title: 'Причепи / будинки на колесах',
				link: '/trailers',
				subcategories: [
					{ title: 'Легковий причіп' },
					{ title: 'Лафет' },
					{ title: 'Напівпричіп' },
					{ title: 'Бортовий напівпричіп' },
					{ title: 'Вантажний причіп' },
					{ title: 'Причіп контейнеровоз' },
					{ title: 'Причіп зерновоз' },
					{ title: 'Самоскид напівпричіп' },
					{ title: 'Трал' },
					{ title: 'Торговий причіп' },
					{ title: 'Тракторний причіп' },
					{ title: 'Причіп фургон' },
					{ title: 'Причепи цистерни' },
					{ title: 'Автодім' },
					{ title: 'Кемпінг' },
					{ title: 'Причіп дача' },
					{ title: 'Інші причепи' },
				],
			},
			{
				title: 'Спецтехніка',
				link: '/special-equipment',
				subcategories: [
					{ title: 'Бульдозери / трактори' },
					{ title: 'Комунальна техніка' },
					{ title: 'Навантажувачі' },
					{ title: 'Самоскиди' },
					{ title: 'Будівельна техніка' },
					{ title: 'Екскаватори' },
					{ title: 'Автовишки' },
					{ title: 'Мінінавантажувач' },
					{ title: 'Бетонозмішувачі (міксери)' },
					{ title: 'Бетононасоси' },
					{ title: 'Бурова установка' },
					{ title: 'Сміттєвоз' },
					{ title: 'Лісозаготівельна техніка' },
					{ title: 'Машина асенізатор (вакуумна)' },
					{ title: 'Автокрани та маніпулятори' },
					{ title: 'Автогрейдер' },
					{ title: 'Асфальтоукладач' },
					{ title: 'Дорожній каток' },
					{ title: 'Всюдиходи' },
					{ title: 'Обладнання для спецтехніки' },
					{ title: 'Інша спецтехніка' },
				],
			},
			{
				title: 'Сільгосптехніка',
				link: '/agricultural-equipment',
				subcategories: [
					{ title: 'Трактор сільськогосподарський' },
					{ title: 'Мотоблок' },
					{ title: 'Мотокультиватор' },
					{ title: 'Міні-трактор' },
					{ title: 'Комбайн' },
					{ title: 'Навісне та додаткове обладнання' },
					{ title: 'Інша сільгосптехніка' },
					{ title: 'Інші' },
				],
			},
			{
				title: 'Автомобілі з Польщі',
				link: '/polish-cars',
			},
			{
				title: 'Вантажівки та спецтехніка з Польщі',
				link: '/polish-trucks',
			},
		],
	},
	{
		title: 'Запчастини для транспорту',
		img: 'category/parts.png',
		color: '#fff6d9',
		link: '/parts',
		subcategories: [
			{
				title: 'Шини, диски і колеса',
				link: '/tires_wheels',
				subcategories: [
					{ title: 'Автошини' },
					{ title: 'Диски' },
					{ title: 'Колеса в зборі' },
					{ title: 'Ковпаки' },
					{ title: 'Мотошини' },
					{ title: 'Мото диски та колеса' },
				],
			},
			{
				title: 'Запчастини для іншої техніки',
				link: '/other',
				subcategories: [
					{ title: 'Для вантажівок' },
					{ title: 'Для автобусів' },
					{ title: 'Для сільгосптехніки' },
					{ title: 'Для спецтехніки' },
					{ title: 'Для водного транспорту' },
					{ title: 'Для інших видів техніки' },
				],
			},
			{
				title: 'Мотозапчастини',
				link: '/motorcycle-parts',
				subcategories: [
					{
						title: 'Акумулятори',
						subcategories: [
							{ title: 'Для скутерів' },
							{ title: 'Для мотоциклів' },
							{ title: 'Для мопедів' },
							{ title: 'Інші' },
						],
					},
					{
						title: 'Амортизатори та підвіска',
						subcategories: [
							{ title: 'Задні амортизатори' },
							{ title: 'Передні амортизатори' },
							{ title: 'Сайлентблоки' },
							{ title: 'Сальники, пильовики амортизатора' },
							{ title: 'Траверси' },
							{ title: 'Інші' },
						],
					},
					{ title: 'Варіатори та редуктори' },
					{ title: 'Вихлопні системи, прямоструми, глушники' },
					{ title: 'Запчастини двигуна' },
					{ title: 'Коробка передач' },
					{ title: 'Ніжки та педалі' },
					{ title: 'Освітлення та лампи' },
					{ title: 'Підшипники' },
					{ title: 'Привід та ходова' },
					{ title: 'Рама, кронштейни та маятники' },
					{
						title: 'Кермо та управління',
						subcategories: [
							{ title: 'Кермо' },
							{ title: 'Рукоятки та гріпси' },
							{ title: 'Кермові демпфери' },
							{ title: 'Важелі' },
							{ title: 'Інші' },
						],
					},
					{ title: 'Сидіння' },
					{ title: 'Система охолодження' },
					{ title: 'Зчеплення' },
					{
						title: 'Паливна система',
						subcategories: [
							{ title: 'Бензобаки, кришки, датчики' },
							{ title: 'Карбюратори' },
							{ title: 'Інші' },
						],
					},
					{ title: 'Гальмівна система' },
					{ title: 'Троси та шланги' },
					{
						title: 'Фільтри',
						subcategories: [
							{ title: 'Повітряні' },
							{ title: 'Мастильні' },
							{ title: 'Паливні' },
							{ title: 'Інші' },
						],
					},
					{ title: 'Ланцюги та зірочки' },
					{
						title: 'Електрика',
						subcategories: [
							{ title: 'Генератори та магнето' },
							{ title: 'Замки запалювання' },
							{ title: 'Котушки запалювання' },
							{ title: 'Комутатори' },
							{ title: 'Реле' },
							{ title: 'Свічки запалювання' },
							{ title: 'Стартери' },
							{ title: 'Інші' },
						],
					},
					{ title: 'Інші мотозапчастини' },
				],
			},
			{
				title: 'Мотоекіпірування',
				link: '/motorcycle-gear',
				subcategories: [
					{ title: 'Мотошоломи' },
					{ title: 'Мотокуртки' },
					{ title: 'Мотоштани' },
					{ title: 'Мотоботи, моточеревики' },
					{ title: 'Мотокомбінезони' },
					{ title: 'Моторукавички' },
					{ title: 'Мотодощовики, мотобахіли' },
					{ title: 'Мотозахист' },
					{ title: 'Підшоломники' },
					{ title: 'Інше мотоекіпірування' },
				],
			},
			{
				title: 'Мотоаксесуари',
				link: '/motorcycle-accessories',
				subcategories: [
					{ title: 'Бризковики' },
					{ title: 'Тримач для телефона, планшета' },
					{ title: 'Інструменти' },
					{ title: 'Кріплення для номерів на мотоцикл' },
					{ title: 'Дзеркала на мотоцикл' },
					{ title: 'Наклейки на мотоцикл, скутер' },
					{ title: 'Обтічники та вітрове скло' },
					{ title: 'Відбійники (крашпеди)' },
					{ title: 'Панельні прилади' },
					{ title: 'Переговорні пристрої' },
					{ title: 'Підніжки' },
					{ title: 'Протиугінні системи' },
					{ title: 'Стайлінг' },
					{ title: 'Стенди та підйомники' },
					{ title: 'Чохли та накидки для мотоцикла' },
					{ title: 'Мотосумки, кофри, рюкзаки' },
					{ title: 'Інші мотоаксесуари' },
				],
			},
			{
				title: 'Аксесуари для авто',
				link: '/car-accessories',
				subcategories: [
					{ title: 'Авто інструменти, набори ключів' },
					{ title: 'Автоковрики' },
					{ title: 'Автомобільний органайзер' },
					{ title: 'Автонасоси, компресори, манометри' },
					{ title: 'Автоподушки' },
					{ title: 'Автосигналізації, блокувачі' },
					{ title: 'Автохолодильники' },
					{ title: 'Автошторки' },
					{ title: 'Ароматизатори, озонатори' },
					{ title: 'Багажники' },
					{ title: 'Бризковики' },
					{ title: 'Вентилятор в авто' },
					{ title: 'Вогнегасник, аптечка, аварійка' },
					{ title: 'Декоративна підсвітка авто' },
					{ title: 'Для тюнінгу' },
					{ title: 'Дефлектори' },
					{ title: 'Домкрати' },
					{ title: 'Елементи кріплення' },
					{ title: 'Каністри' },
					{ title: 'Ланцюги, браслети протиковзання' },
					{ title: 'Лебідки' },
					{ title: 'Наклейки, емблеми, значки' },
					{ title: 'Насадки на глушник' },
					{ title: 'Підігрів сидінь та автомасажери' },
					{ title: 'Підставки та тримачі' },
					{ title: 'Повітрозабірники' },
					{ title: 'Пороги та накладки' },
					{ title: 'Пускові та зарядні пристрої' },
					{ title: 'Рамки номерного знаку' },
					{ title: 'Салонний годинник, прилади, БК' },
					{ title: 'Тонування та сонцезахист' },
					{ title: 'Фаркопи' },
					{ title: 'Чохли, тенти, накидки' },
					{ title: 'Шумоізоляція' },
					{ title: 'Щітки та скребки' },
					{ title: 'Інші автоаксесуари' },
				],
			},
			{
				title: 'Автозвук та мультимедіа',
				link: '/car-audio',
				subcategories: [
					{
						title: 'Автомагнітоли',
						subcategories: [
							{ title: 'Alpine' },
							{ title: 'Pioneer' },
							{ title: 'Blaupunkt' },
							{ title: 'Clarion' },
							{ title: 'Sony' },
							{ title: 'Cyclon' },
							{ title: 'Incar' },
							{ title: 'JVC' },
							{ title: 'Kenwood' },
							{ title: 'LG' },
							{ title: 'Mystery' },
							{ title: 'Philips' },
							{ title: 'Prology' },
							{ title: 'SHUTTLE' },
							{ title: 'Swat' },
							{ title: 'Магнітоли інших марок' },
						],
					},
					{
						title: 'Колонки / сабвуфери',
						subcategories: [
							{ title: 'Alpine' },
							{ title: 'Blaupunkt' },
							{ title: 'DLS' },
							{ title: 'Edge' },
							{ title: 'Focal' },
							{ title: 'Hertz' },
							{ title: 'JBL' },
							{ title: 'JVC' },
							{ title: 'Kenwood' },
							{ title: 'Kicx' },
							{ title: 'Mystery' },
							{ title: 'Pioneer' },
							{ title: 'Sony' },
							{ title: 'Supra' },
							{ title: 'Колонки/сабвуфери інших марок' },
						],
					},
					{
						title: 'Підсилювачі',
						subcategories: [
							{ title: 'Alpine' },
							{ title: 'Blaupunkt' },
							{ title: 'DLS' },
							{ title: 'Ground Zero' },
							{ title: 'Hertz' },
							{ title: 'JBL' },
							{ title: 'JVC' },
							{ title: 'Kenwood' },
							{ title: 'Kicx' },
							{ title: 'Magnat' },
							{ title: 'Mystery' },
							{ title: 'Pioneer' },
							{ title: 'Pride' },
							{ title: 'Sony' },
							{ title: 'Supra' },
							{ title: 'Підсилювачі інших марок' },
						],
					},
					{ title: 'Антени для авто' },
					{ title: 'FM-трансмітери' },
					{ title: 'Кабелі, адаптери, запобіжники' },
					{ title: 'DVD, TV, інша мультимедіа' },
					{ title: 'Інші компоненти' },
				],
			},
			{
				title: 'GPS-навігатори / відеореєстратори',
				link: '/gps_dashcams',
				subcategories: [
					{ title: 'GPS-навігатори' },
					{ title: 'Навігаційні карти та GPS-аксесуари' },
					{ title: 'Відеореєстратори' },
				],
			},
			{
				title: 'Транспорт на запчастини / авторозбірки',
				link: '/parts_transport',
				subcategories: [
					{ title: 'Acura' },
					{ title: 'Audi' },
					{ title: 'BMW' },
					{ title: 'Chevrolet' },
					{ title: 'Chrysler' },
					{ title: 'Citroen' },
					{ title: 'Daewoo' },
					{ title: 'Dodge' },
					{ title: 'Fiat' },
					{ title: 'Ford' },
					{ title: 'Honda' },
					{ title: 'Hyundai' },
					{ title: 'Infiniti' },
					{ title: 'Jeep' },
					{ title: 'Kia' },
					{ title: 'Land Rover' },
					{ title: 'Lexus' },
					{ title: 'Lincoln' },
					{ title: 'Mazda' },
					{ title: 'Mercedes-Benz' },
					{ title: 'Mitsubishi' },
					{ title: 'Nissan' },
					{ title: 'Opel' },
					{ title: 'Peugeot' },
					{ title: 'Porsche' },
					{ title: 'Renault' },
					{ title: 'Rover' },
					{ title: 'Seat' },
					{ title: 'Skoda' },
					{ title: 'Subaru' },
					{ title: 'Suzuki' },
					{ title: 'Toyota' },
					{ title: 'Volkswagen' },
					{ title: 'Volvo' },
					{ title: 'ВАЗ' },
					{ title: 'ГАЗ' },
					{ title: 'ЗАЗ' },
					{ title: 'ИЖ' },
					{ title: 'Москвич' },
					{ title: 'Інший бренд' },
				],
			},
			{
				title: 'Автозапчастини',
				link: '/car-parts',
				subcategories: [
					{
						title: 'Двигун',
						subcategories: [
							{ title: 'Блок циліндрів та його частини' },
							{ title: 'Газорозподільний механізм (ГРМ)' },
							{ title: 'Двигуни у зборі' },
							{ title: 'Кожухи та кришки двигуна' },
							{ title: 'Кривошипно-шатунний механізм' },
							{ title: 'Маховики та їхні компоненти' },
							{ title: 'Подушки двигуна' },
							{ title: 'Підшипники двигуна' },
							{ title: 'Поршнева група' },
							{ title: 'Прокладки та комплекти прокладок' },
							{ title: 'Ролики та натягувачі' },
							{ title: 'Радіатори автомобільні' },
							{ title: 'Сальники та ущільнюючі кільця' },
							{ title: 'Система змащування двигуна' },
							{ title: 'Турбіни, турбокомпресори' },
							{ title: 'Шківи та шпонки двигуна' },
							{ title: 'Інші запчастини двигуна' },
						],
					},
					{
						title: 'Вихлопна система',
						subcategories: [
							{ title: 'Вихлопні колектори' },
							{ title: 'Вихлопні системи в зборі' },
							{ title: 'Глушники' },
							{ title: 'Гофри' },
							{ title: 'Датчики кисневі (лямбда-зонд)' },
							{ title: 'Датчики температури палива, оливи та інші' },
							{ title: 'Каталізатори' },
							{ title: 'Клапани EGR' },
							{ title: "Полум'ягасники" },
							{ title: 'Резонатори' },
							{ title: 'Труби та частини вихлопної системи' },
							{ title: 'Інші запчастини вихлопної системи' },
						],
					},
					{
						title: 'Трансмісія / КПП та АКПП',
						subcategories: [
							{ title: 'Карданні вали' },
							{ title: 'Приводні вали' },
							{ title: 'Варіатор' },
							{ title: 'Вилки та штоки перемикання передач' },
							{ title: 'Гідротрансформатор' },
							{ title: 'Диски фрикційні та віскомуфти' },
							{ title: 'Диференціали (редуктори)' },
							{ title: 'Компоненти КПП / АКПП' },
							{ title: 'Коробки відбору потужності' },
							{ title: 'КПП / АКПП у зборі' },
							{ title: 'Мости трансмісії' },
							{ title: 'Муфти еластичні' },
							{ title: 'Підшипники трансмісії' },
							{ title: 'Циліндри зчеплення' },
							{ title: 'Шруси' },
							{ title: 'Інші запчастини трансмісії' },
						],
					},
					{
						title: 'Кермове управління',
						subcategories: [
							{ title: 'Керма та їхні компоненти' },
							{ title: 'Амортизатори та стабілізатори рульового керування' },
							{ title: 'Кермові вали та їхні компоненти' },
							{ title: 'Гідропідсилювач керма' },
							{ title: 'Накінечники кермові' },
							{ title: 'Педаль газу' },
							{ title: 'Пильовики, відбійники' },
							{ title: 'Рейки кермового управління' },
							{ title: 'Кермові механізми' },
							{ title: 'Кермові тяги' },
							{ title: 'Інші запчастини системи керування' },
						],
					},
					{
						title: 'Ходова частина / підвіска',
						subcategories: [
							{ title: 'Амортизатори' },
							{ title: 'Балки підвіски' },
							{ title: 'Втулки' },
							{ title: 'Кульові опори' },
							{ title: 'Пневморесори, пневмоподушки' },
							{ title: 'Поворотні кулаки' },
							{ title: 'Проставки для збільшення кліренсу' },
							{ title: 'Пружини підвіски' },
							{ title: 'Ресори та їхні складові' },
							{ title: 'Важелі, тяги' },
							{ title: 'Сайлентблоки' },
							{ title: 'Стійки стабілізаторів' },
							{ title: 'Маточини, підшипники маточини' },
							{ title: 'Торсіони' },
							{ title: 'Інші запчастини підвіски' },
						],
					},
					{
						title: 'Паливна система',
						subcategories: [
							{ title: 'Паливні насоси' },
							{ title: 'Баки та бачки паливної системи' },
							{ title: 'Впускні колектори' },
							{ title: 'Дросельні заслінки' },
							{ title: 'Карбюратори та комплектуючі' },
							{ title: 'Розпилювачі та паливні форсунки' },
							{ title: 'Регулятори тиску палива' },
							{ title: 'Інші запчастини паливної системи' },
						],
					},
					{
						title: 'Гальмівна система',
						subcategories: [
							{ title: 'Барабани гальмівні' },
							{ title: 'Деталі гальмівних систем ABS, EBD' },
							{ title: 'Гальмівні камери та енергоакумулятори' },
							{ title: 'Накладки гальмівні' },
							{ title: 'Ресивери' },
							{ title: 'Ретардери' },
							{ title: 'Гальмівні диски' },
							{ title: 'Гальмівні колодки дискові' },
							{ title: 'Гальмівні колодки барабанні' },
							{ title: 'Гальмівні супорти' },
							{ title: 'Гальмівні циліндри' },
							{ title: 'Гальмівні шланги' },
							{ title: 'Підсилювачі гальм та їхні компоненти' },
							{ title: 'Інші запчастини гальмівної системи' },
						],
					},
					{
						title: 'Кузовні запчастини',
						subcategories: [
							{ title: 'Багажники, задні панелі та їхні деталі' },
							{ title: 'Бампери' },
							{ title: 'Підсилювачі бампера, буфер бампера' },
							{ title: 'Двері' },
							{ title: 'Захист картера та КПП' },
							{ title: 'Капоти та їхні частини' },
							{ title: 'Амортизатори капота, багажника' },
							{ title: 'Крила та їхні частини' },
							{ title: 'Кузови легкових автомобілів' },
							{ title: 'Дверні замки та ключі' },
							{ title: 'Автомобільні люки' },
							{ title: 'Лонжерони, підрамники' },
							{ title: 'Лючки, кришки бензобака' },
							{ title: 'Нижня частина кузова та рама автомобіля' },
							{ title: 'Передня панель, телевізор' },
							{ title: 'Решітка радіатора' },
							{ title: 'Інші кузовні запчастини' },
						],
					},
					{
						title: 'Деталі салону',
						subcategories: [
							{ title: 'Автосидіння, крісла' },
							{ title: 'Бардачки' },
							{ title: 'Дверні карти, обшивка дверей' },
							{ title: 'Дзеркала' },
							{ title: 'Задня полиця' },
							{ title: 'Кнопки / Перемикачі' },
							{ title: 'Матеріал для підлоги' },
							{ title: 'Попільничка' },
							{ title: 'Пластик салону' },
							{ title: 'Підлокітник' },
							{ title: 'Підсклянник' },
							{ title: 'Подушки безпеки, AIRBAG' },
							{ title: 'Прикурювач' },
							{ title: 'Ремені безпеки та натягувач' },
							{ title: 'Кермо' },
							{ title: 'Ручки дверей та салону' },
							{ title: 'Ручки КПП' },
							{ title: 'Торпедо, консоль' },
							{ title: 'Інші деталі салону' },
						],
					},
					{
						title: 'Кондиціонер, обігрівач, вентиляція',
						subcategories: [
							{ title: 'Автомобільні кондиціонери у зборі' },
							{ title: 'Автономні обігрівачі' },
							{ title: 'Блок управління кондиціонером' },
							{ title: 'Вентилятори, системи кондиціювання та опалення' },
							{ title: 'Випарники' },
							{ title: 'Компресори' },
							{ title: 'Конденсатори кондиціонера' },
							{ title: 'Радіатори обігрівачів' },
							{ title: 'Трубки, шланги, повітропроводи' },
							{ title: 'Інші запчастини кондиціонерів та опалення' },
						],
					},
					{
						title: 'Система подачі повітря',
						subcategories: [
							{ title: 'Впускний та випускний колектори' },
							{ title: 'Інтеркулери' },
							{ title: 'Корпуси повітряного фільтра' },
							{ title: 'Патрубки турбіни та інтеркулера' },
							{ title: 'Інші запчастини подачі повітря' },
						],
					},
					{
						title: 'Система запалювання',
						subcategories: [
							{ title: 'Високовольтні дроти запалювання' },
							{ title: 'Замки запалювання та ключі' },
							{ title: 'Котушки запалювання' },
							{ title: 'Свічки запалювання' },
							{ title: 'Свічки розжарювання' },
							{ title: 'Стартер, запчастини стартера' },
							{ title: 'Трамблери' },
							{ title: 'Інші запчастини системи запалення' },
						],
					},
					{
						title: 'Система очищення вікон та фар',
						subcategories: [
							{ title: 'Бачки та кришки омивачів' },
							{ title: 'Моторчики двірників' },
							{ title: 'Насоси омивача' },
							{ title: 'Гумки для склоочисників' },
							{ title: 'Форсунки омивача' },
							{ title: 'Двірники' },
							{ title: 'Інші запчастини очищення вікон та фар' },
						],
					},
					{
						title: 'Фари та освітлення',
						subcategories: [
							{ title: 'Передні фари' },
							{ title: 'Задні фари' },
							{ title: 'Протитуманні фари' },
							{ title: 'Денні ходові вогні' },
							{ title: 'Ксенон' },
							{ title: 'Лампочки' },
							{ title: 'Відбивачі, корпуси фар' },
							{ title: 'Повторювачі поворотів' },
							{ title: "Освітлення інтер'єру" },
							{ title: 'Інші елементи освітлення' },
						],
					},
					{
						title: 'Електрообладнання',
						subcategories: [
							{ title: 'Акумулятори' },
							{ title: 'Блоки керування' },
							{ title: 'Генератор, запчастини генератора' },
							{ title: 'Кнопки та вимикачі' },
							{ title: 'Панелі приладів' },
							{ title: 'Запобіжники, переривники' },
							{ title: 'Прикурювачі та комплектуючі' },
							{ title: 'Реле' },
							{ title: 'Звукові сигнали' },
							{ title: 'Електропроводка та компоненти' },
							{ title: 'Інше електрообладнання' },
						],
					},
					{
						title: 'Фільтри',
						subcategories: [
							{ title: 'Повітряні фільтри' },
							{ title: 'Мастильні фільтри' },
							{ title: 'Паливні фільтри' },
							{ title: 'Фільтри салону' },
							{ title: 'Фільтри ГБО' },
							{ title: 'Фільтри інших типів' },
						],
					},
					{
						title: 'Автоскло',
						subcategories: [
							{ title: 'Скло вітрове (лобове)' },
							{ title: 'Бічне скло' },
							{ title: 'Скло дверей' },
							{ title: 'Заднє скло' },
							{ title: 'Автоскло інших видів' },
						],
					},
					{
						title: 'ГБО',
						subcategories: [
							{ title: 'Балони газові' },
							{ title: 'Редуктори газові' },
							{ title: 'Форсунки газові' },
							{ title: 'Інші компоненти ГБО' },
						],
					},
					{ title: 'Інші види запчастин' },
				],
			},
			{
				title: 'Мастила та автохімія',
				link: '/oils_chemicals',
				subcategories: [
					{ title: 'Моторні мастила' },
					{ title: 'Трансмісійні мастила' },
					{ title: 'Гідравлічні мастила' },
					{ title: 'Мастила для мототехніки' },
					{ title: 'Автокосметика та автохімія' },
					{ title: 'Інші мастила та рідини' },
				],
			},
		],
	},
	{
		title: 'Робота',
		img: 'category/work.png',
		link: '/work',
		color: '#ceddff',
		subcategories: [
			{
				title: 'Медицина / фармацевтика',
				link: '/medicine_pharmaceuticals',
				subcategories: [
					{ title: 'Медсестра' },
					{ title: 'Стоматолог' },
					{ title: 'Фармацевт' },
					{ title: 'Інше' },
				],
			},
			{
				title: 'Часткова зайнятість',
				link: '/part-time',
				subcategories: [],
			},
			{
				title: 'Краса / фітнес / спорт',
				link: '/beauty_fitness_sports',
				subcategories: [
					{ title: 'Перукар' },
					{ title: 'Майстер манікюру' },
					{ title: 'Адміністратор' },
					{ title: 'Масажист' },
					{ title: 'Косметолог' },
					{ title: 'Тренер' },
					{ title: 'Інше' },
				],
			},
			{
				title: 'Логістика / Склад / Доставка',
				link: '/logistics_warehouse_delivery',
				subcategories: [
					{ title: 'Водій' },
					{ title: 'Вантажник' },
					{ title: "Кур'єр" },
					{ title: 'Комірник' },
					{ title: 'Диспетчер' },
					{ title: 'Експедитор' },
					{ title: 'Далекобійник' },
					{ title: 'Таксист' },
					{ title: 'Інше' },
				],
			},
			{
				title: 'Освіта / переклад',
				link: '/education_translation',
				subcategories: [
					{ title: 'Викладач / Вчитель' },
					{ title: 'Вихователь' },
					{ title: 'Репетитор' },
					{ title: 'Інше' },
				],
			},
			{
				title: 'Виробництво / робітничі спеціальності',
				link: '/production_blue-collar-jobs',
				subcategories: [
					{ title: 'Електрик' },
					{ title: 'Столяр' },
					{ title: 'Швачка, кравець' },
					{ title: 'Токар' },
					{ title: 'Машиніст екскаватора' },
					{ title: 'Конструктор' },
					{ title: 'Комплектувальник' },
					{ title: 'Складальник меблів' },
					{ title: 'Різноробочий' },
					{ title: 'Зварювальник' },
					{ title: 'Складальник' },
					{ title: 'Слюсар' },
					{ title: 'Маляр' },
					{ title: 'Пакувальник' },
					{ title: 'Монтажник' },
					{ title: 'Механік' },
					{ title: 'Підсобник' },
					{ title: 'Оператор ЧПУ' },
					{ title: 'Технолог' },
					{ title: 'Інше' },
				],
			},
			{
				title: 'Роздрібна торгівля / продажі / закупки',
				link: '/retail_sales_purchasing',
				subcategories: [
					{ title: 'Мерчендайзер' },
					{ title: 'Менеджер з продажу' },
					{ title: 'Продавець' },
					{ title: 'Супервайзер' },
					{ title: 'Флорист' },
					{ title: 'Продавець-консультант' },
					{ title: 'Торговий представник' },
					{ title: 'Менеджер інтернет-магазину' },
					{ title: 'Касир' },
					{ title: 'Менеджер по роботі з клієнтами' },
					{ title: 'Товарознавець' },
					{ title: 'Керівник відділу продажів' },
					{ title: 'Менеджер по закупці' },
					{ title: 'Адміністратор' },
					{ title: 'Пекар' },
					{ title: 'Інше' },
				],
			},
			{
				title: 'Реклама / дизайн / PR',
				link: '/advertising_design_pr',
				subcategories: [
					{ title: 'Промоутер' },
					{ title: 'Дизайнер' },
					{ title: 'Маркетолог' },
					{ title: 'SMM-менеджер' },
					{ title: 'Контент-менеджер' },
					{ title: 'Копірайтер' },
					{ title: 'Інше' },
				],
			},
			{
				title: "IT / комп'ютери",
				link: '/it_computers',
				subcategories: [
					{ title: 'Оператор ПК' },
					{ title: 'Майстер з ремонту' },
					{ title: 'Системний адміністратор' },
					{ title: 'Інше' },
				],
			},
			{
				title: 'Будівництво / облицювальні роботи',
				link: '/construction_finishing_works',
				subcategories: [
					{ title: 'Різноробочий' },
					{ title: 'Муляр' },
					{ title: 'Плиточник' },
					{ title: 'Монтажник' },
					{ title: 'Зварювальник' },
					{ title: 'Будівельник' },
					{ title: 'Маляр' },
					{ title: 'Виконроб' },
					{ title: 'Сантехнік' },
					{ title: 'Фасадник' },
					{ title: 'Штукатур' },
					{ title: 'Електрик' },
					{ title: 'Інше' },
				],
			},
			{
				title: 'Інші сфери занять',
				link: '/other',
			},
			{
				title: 'Охорона / безпека',
				link: '/security_safety',
				subcategories: [
					{ title: 'Охоронець' },
					{ title: 'Сторож' },
					{ title: 'Інше' },
				],
			},
			{
				title: 'Культура / мистецтво / розваги',
				link: '/culture_art_entertainment',
				subcategories: [
					{ title: 'Фотограф' },
					{ title: 'Модель' },
					{ title: 'Аніматор' },
					{ title: 'Інше' },
				],
			},
			{
				title: 'Клінінг / Домашній персонал',
				link: '/cleaning_domestic',
				subcategories: [
					{ title: 'Доглядальниця' },
					{ title: 'Прибиральниця' },
					{ title: 'Двірник' },
					{ title: 'Няня' },
					{ title: 'Домробітниця' },
					{ title: 'Інше' },
				],
			},
			{
				title: 'Нерухомість',
				link: '/real-estate',
				subcategories: [
					{ title: 'Ріелтор' },
					{ title: 'Менеджер з продажу' },
					{ title: 'Брокер' },
					{ title: 'Інше' },
				],
			},
			{
				title: "Початок кар'єри / Студенти",
				link: '/career-start_students',
			},
			{
				title: 'Адміністративний персонал / HR / Секретаріат',
				link: '/administrative_hr_secretarial',
				subcategories: [
					{ title: 'Адміністратор' },
					{ title: 'Секретар' },
					{ title: 'Офіс менеджер' },
					{ title: 'HR' },
					{ title: 'Інше' },
				],
			},
			{
				title: 'Банки / фінанси / страхування / юриспруденція',
				link: '/banking_finance_insurance_law',
				subcategories: [{ title: 'Юрист' }, { title: 'Інше' }],
			},
			{
				title: 'Колл-центри / Телекомунікації',
				link: '/call-centers_telecommunications',
				subcategories: [
					{ title: 'Оператор колл-центру' },
					{ title: 'Оператор чату' },
					{ title: 'Інше' },
				],
			},
			{
				title: 'Сільське і лісове господарство / агробізнес',
				link: '/agriculture-forestry_agribusiness',
				subcategories: [
					{ title: 'Агроном' },
					{ title: 'Тракторист' },
					{ title: 'Пилорамщик' },
					{ title: 'Інше' },
				],
			},
			{
				title: 'Робота за кордоном',
				link: '/work-abroad',
				subcategories: [
					{ title: 'Різноробочий' },
					{ title: 'Кухар' },
					{ title: 'Водій' },
					{ title: 'Няня' },
					{ title: 'Доглядальниця' },
					{ title: 'Зварювальник' },
					{ title: 'Будівельник' },
					{ title: 'Пакувальник' },
					{ title: 'Інше' },
				],
			},
			{
				title: 'Бухгалтерія',
				link: '/accounting',
				subcategories: [
					{ title: 'Бухгалтер' },
					{ title: 'Аудитор' },
					{ title: 'Інше' },
				],
			},
			{
				title: 'Готельно-ресторанний бізнес / Туризм',
				link: '/hotel-restaurant-business_tourism',
				subcategories: [
					{ title: 'Адміністратор' },
					{ title: 'Покоївка' },
					{ title: 'Менеджер' },
					{ title: 'Бариста' },
					{ title: 'Кухар' },
					{ title: 'Бармен' },
					{ title: 'Офіціант' },
					{ title: 'Кондитер' },
					{ title: 'Пекар' },
					{ title: 'Помічник кухаря' },
					{ title: 'Сушист' },
					{ title: 'Посудомийниця' },
					{ title: 'Піцайоло' },
					{ title: 'Інше' },
				],
			},
			{
				title: 'СТО / автомийки',
				link: '/auto-service_car-washes',
				subcategories: [
					{ title: 'Автослюсар' },
					{ title: 'Мийник' },
					{ title: 'Механік' },
					{ title: 'Автомаляр' },
					{ title: 'Автоелектрик' },
					{ title: 'Рихтувальник' },
					{ title: 'Шиномонтажник' },
					{ title: 'Інше' },
				],
			},
			{
				title: 'Служба в Силах оборони',
				link: '/military-service',
			},
			{
				title: 'Робота швачкою',
				link: '/seamstress',
			},
		],
	},
	{
		title: 'Тварини',
		img: 'category/pets.png',
		color: '#c8f8f6',
		link: '/animals',
		subcategories: [
			{
				title: 'Собаки',
				link: '/dogs',
			},
			{
				title: 'Коти',
				link: '/cats',
			},
			{
				title: 'Інші тварини',
				link: '/other',
			},
			{
				title: 'Зоотовари',
				link: '/pet-supplies',
			},
			{
				title: 'Бюро знахідок',
				link: '/lost-and-found',
			},
			{
				title: "В'язка",
				link: '/breeding',
			},
			{
				title: 'Пташки',
				link: '/birds',
			},
			{
				title: 'Гризуни',
				link: '/rodents',
			},
			{
				title: 'Рептилії',
				link: '/reptiles',
			},
			{
				title: 'Акваріумістика',
				link: '/aquariums',
			},
			{
				title: 'Сільгосп тварини',
				link: '/farm-animals',
			},
			{
				title: "Безкоштовно (тварини і в'язка)",
				link: '/free-animals-breeding',
			},
		],
	},
	{
		title: 'Дім і сад',
		link: '/household',
		img: 'category/household.png',
		color: '#ffd6c9',
		subcategories: [
			{
				title: 'Кімнатні рослини',
				link: '/indoor-plants',
			},
			{
				title: 'Меблі',
				link: '/furniture',
				subcategories: [
					{ title: 'Меблі для вітальні' },
					{ title: 'Меблі для спальні' },
					{ title: 'Меблі для передпокою' },
					{ title: 'Кухонні меблі' },
					{ title: 'Меблі для ванної кімнати' },
					{ title: 'Офісні меблі' },
					{ title: 'Меблі на замовлення' },
				],
			},
			{
				title: "Предмети інтер'єру",
				link: '/interior-items',
				subcategories: [
					{ title: 'Освітлення' },
					{ title: 'Текстиль' },
					{ title: 'Декор вікон' },
				],
			},
			{
				title: 'Інші товари для дому',
				link: '/other',
			},
			{
				title: 'Продукти харчування / напої',
				link: '/food_beverages',
			},
			{
				title: 'Господарський інвентар / побутова хімія',
				link: '/household-inventory_chemicals',
			},
			{
				title: 'Садовий інвентар',
				link: '/garden-inventory',
			},
			{
				title: 'Канцтовари / витратні матеріали',
				link: '/stationery_consumables',
			},
			{
				title: 'Будівництво / ремонт',
				link: '/construction_repair',
				subcategories: [
					{ title: 'Вентиляція' },
					{ title: 'Сантехніка' },
					{ title: 'Опалення' },
					{ title: 'Електрика' },
					{ title: 'Пиломатеріали' },
					{ title: 'Оздоблювальні та облицювальні матеріали' },
					{ title: 'Вікна / двері / скло / дзеркала' },
					{ title: 'Лакофарбові матеріали' },
					{ title: 'Металопрокат / арматура' },
					{ title: 'Елементи кріплення' },
					{ title: 'Цегла / бетон / піноблоки' },
					{ title: 'Інші будматеріали' },
				],
			},
			{
				title: 'Інструменти',
				link: '/tools',
				subcategories: [
					{ title: 'Генератори' },
					{ title: 'Ручний інструмент' },
					{ title: 'Електроінструмент' },
					{ title: 'Пневмоінструмент' },
					{ title: 'Інший інструмент' },
				],
			},
			{
				title: 'Посуд / кухонне приладдя',
				link: '/dishes_kitchenware',
			},
			{
				title: 'Сад / город',
				link: '/garden',
			},
		],
	},
	{
		title: 'Електроніка',
		link: '/electronics',
		img: 'category/electronic.png',
		color: '#ffce32',
		subcategories: [
			{
				title: "Комп'ютери та комплектуючі",
				link: '/computers_components',
			},
			{
				title: 'Телефони та аксесуари',
				link: '/phones_accessories',
			},
			{
				title: 'Ігри та ігрові приставки',
				link: '/games_gaming-consoles',
			},
			{
				title: 'Техніка для кухні',
				link: '/kitchen-appliances',
			},
			{
				title: 'Техніка для дому',
				link: '/home-appliances',
			},
			{
				title: 'Індивідуальний догляд',
				link: '/personal-care',
			},
			{
				title: 'Кліматичне обладнання',
				link: '/climate-equipment',
			},
			{
				title: 'Аксесуари й комплектуючі',
				link: '/accessories_components',
			},
			{
				title: 'Аудіотехніка',
				link: '/audio-equipment',
			},
			{
				title: 'Тв / відеотехніка',
				link: '/tv_video-equipment',
			},
			{
				title: 'Фото / відео',
				link: '/photo_video',
			},
			{
				title: 'Інша електроніка',
				link: '/other',
			},
			{
				title: 'Ноутбуки та аксесуари',
				link: '/laptops_accessories',
			},
			{
				title: 'Планшети / ел. книги та аксесуари',
				link: '/tablets_ebooks_accessories',
			},
			{
				title: 'Ремонт та обслуговування техніки',
				link: '/electronics_repair-maintenance',
			},
		],
	},
	{
		title: 'Бізнес та послуги',
		link: '/services',
		color: '#ceddff',
		img: 'category/services.png',
		subcategories: [
			{
				title: 'Продаж бізнесу',
				link: '/business-for-sale',
			},
			{
				title: 'Продаж обладнання для бізнесу',
				link: '/business-equipment-for-sale',
			},
			{
				title: 'Авто / мото послуги',
				link: '/auto_moto',
			},
			{
				title: 'Інші послуги',
				link: '/other',
			},
			{
				title: 'Будівництво та ремонт',
				link: '/construction_repair',
			},
			{
				title: 'Туризм / іміграція',
				link: '/tourism_immigration',
			},
			{
				title: 'Перевезення та послуги спецтехніки',
				link: '/transportation-special-equipment',
			},
			{
				title: "Краса / здоров'я",
				link: '/beauty_health',
			},
			{
				title: 'Послуги для тварин',
				link: '/services-for-animals',
			},
			{
				title: 'Фото та відеозйомка',
				link: '/photo-video',
			},
			{
				title: 'Послуги освіти та спорту',
				link: '/education-sports',
			},
			{
				title: 'Догляд за дітьми та літніми людьми',
				link: '/care-for-children-elderly',
			},
			{
				title: 'Сировина / матеріали',
				link: '/raw_materials',
			},
			{
				title: 'Ремонт та обслуговування техніки',
				link: '/electronics-repair-maintenance',
			},
			{
				title: 'Побутові послуги',
				link: '/household',
			},
			{
				title: 'Клінінг',
				link: '/cleaning',
			},
			{
				title: 'Організація свят',
				link: '/event-organization',
			},
			{
				title: 'Ритуальні послуги',
				link: '/funeral',
			},
			{
				title: 'Прийом вторсировини',
				link: '/recycling',
			},
			{
				title: 'Ділові послуги',
				link: '/business',
			},
		],
	},
	{
		title: 'Оренда та прокат',
		link: '/rent',
		color: '#c8f8f6',
		img: 'category/rent.png',
		subcategories: [
			{
				title: 'Оренда транспорту та спецтехніки',
				link: '/rental-transport_special-equipment',
			},
			{
				title: 'Прокат велосипедів і мото',
				link: '/bike-moto',
			},
			{
				title: 'Оренда обладнання',
				link: '/equipment',
			},
			{
				title: 'Прокат інструментів',
				link: '/tool',
			},
			{
				title: 'Прокат товарів мед призначення',
				link: '/medical-equipment',
			},
			{
				title: 'Прокат техніки та електроніки',
				link: '/technology_electronics',
			},
			{
				title: 'Прокат товарів для заходів',
				link: '/event',
			},
			{
				title: 'Прокат спорт і туристичних товарів',
				link: '/sports-tourist',
			},
			{
				title: 'Прокат одягу та аксесуарів',
				link: '/clothing_accessories',
			},
			{
				title: 'Прокат дитячого одягу та товарів',
				link: '/childrens_clothing',
			},
			{
				title: 'Інші товари на прокат',
				link: '/other',
			},
		],
	},
	{
		title: 'Мода і стиль',
		link: '/fashion',
		img: 'category/fashion.png',
		color: '#ffd6c9',
		subcategories: [
			{
				title: "Краса / здоров'я",
				link: '/beauty_health',
			},
			{
				title: 'Для весілля',
				link: '/wedding',
			},
			{
				title: 'Аксесуари',
				link: '/accessories',
			},
			{
				title: 'Наручні годинники',
				link: '/wristwatches',
			},
			{
				title: 'Подарунки',
				link: '/gifts',
			},
			{
				title: 'Мода різне',
				link: '/fashion-various',
			},
			{
				title: 'Чоловіча білизна та плавки',
				link: '/mens-underwear_swimwear',
			},
			{
				title: 'Жіноча білизна та купальники',
				link: '/womens-underwear_swimwear',
			},
			{
				title: 'Одяг для вагітних',
				link: '/maternity-clothing',
			},
			{
				title: 'Головні убори',
				link: '/headwear',
			},
			{
				title: 'Чоловіче взуття',
				link: '/mens-footwear',
			},
			{
				title: 'Жіноче взуття',
				link: '/womens-footwear',
			},
			{
				title: 'Жіночий одяг',
				link: '/womens-clothing',
			},
			{
				title: 'Чоловічий одяг',
				link: '/mens-clothing',
			},
			{
				title: 'Спецодяг, спецвзуття та аксесуари',
				link: '/workwear_footwear_accessories',
			},
		],
	},
	{
		title: 'Хобі, відпочинок і спорт',
		link: '/hobby',
		img: 'category/hobby.png',
		color: '#fff6d9',
		subcategories: [
			{
				title: 'Музичні інструменти',
				link: '/musical-instruments',
			},
			{
				title: 'Книги / журнали',
				link: '/books_magazines',
			},
			{
				title: 'Антикваріат / колекції',
				link: '/antiques_collectibles',
			},
			{
				title: 'Квитки',
				link: '/tickets',
			},
			{
				title: 'Пошук попутників',
				link: '/travel-companions',
			},
			{
				title: 'Пошук гуртів / музикантів',
				link: '/bands-musicians-search',
			},
			{
				title: 'CD / DVD / Платівки',
				link: '/cd_dvd_vinyl',
			},
			{
				title: 'Спорт / відпочинок',
				link: '/sports_recreation',
			},
			{
				title: 'Інше',
				link: '/other',
			},
			{
				title: 'Мілітарія',
				link: '/military',
			},
			{
				title: 'Вело',
				link: '/bicycles',
			},
			{
				title: 'Квадрокоптери та аксесуари',
				link: '/quadcopters-accessories',
			},
		],
	},
	{
		title: 'Віддам безкоштовно',
		link: '/free',
		img: 'category/free.png',
		color: '#3a77ff',
	},
	{
		title: 'Обмін',
		link: '/exchange',
		img: 'category/exchange.png',
		color: '#23e5db',
	},
]
